import { DMCaselet, DMConceptGuide } from "./types";

// ==========================================
// THE 12 CANONICAL XAT DECISION MAKING CONCEPTS
// ==========================================

export const XAT_DM_CONCEPTS: DMConceptGuide[] = [
  {
    id: "dm-concept-01",
    number: 1,
    title: "Identifying the Core Problem",
    corePrinciple: "Distinguish symptoms from root causes. An action that addresses only a symptom while leaving the root cause unaddressed invariably worsens the system.",
    overview: "In XAT caselets, multiple issues are presented simultaneously—dropping morale, declining revenues, customer complaints, regulatory scrutiny. The test requires identifying the underlying causal structural defect rather than reacting emotionally to superficial symptoms.",
    frameworkSteps: [
      "1. Catalogue all presented pain points (e.g. employee attrition, delayed shipments).",
      "2. Apply root-cause tracing: Why did attrition spike? (Unclear evaluation criteria). Why are shipments delayed? (Supply-chain software incompatibility).",
      "3. Discard peripheral issues that naturally resolve once the central bottleneck is removed.",
      "4. Formulate the problem statement in terms of systemic accountability, not personal blame.",
    ],
    decisionRules: [
      "Never select an option that solves an immediate symptom by creating a worse systemic distortion.",
      "Reject punitive measures aimed at individuals when the workflow architecture itself is defective.",
      "The most effective first step is always diagnostic verification when data is ambiguous.",
    ],
    commonTraps: [
      "Treating customer outrage as the core problem rather than the defective QA checkpoint that permitted the faulty unit to leave the factory floor.",
      "Confusing urgency with structural importance.",
    ],
    xlriPerspective: "XLRI values leaders who stay calm under public pressure and systematically isolate operational fundamentals rather than announcing hasty PR cosmetic fixes.",
    caseletExample: {
      situation: "A retail chain notices declining store footfall and rising returns. Store managers blame aggressive online e-commerce discounting.",
      trapOption: "Launch an expensive 50% clearance sale immediately to match online prices.",
      whyTrap: "Eats profit margins without diagnosing why customer returns escalated in the first place.",
      optimalOption: "Audit return merchandise reports to investigate defect patterns while surveying exiting shoppers on store hygiene and staff attentiveness.",
      whyOptimal: "Addresses product quality and in-store experience defects directly before burning capital on reactionary price wars.",
    },
  },
  {
    id: "dm-concept-02",
    number: 2,
    title: "Stakeholder Analysis",
    corePrinciple: "Every managerial choice redistributes benefits and burdens across internal and external stakeholders. Sound decisions balance legitimate claims without sacrificing core fiduciary duty.",
    overview: "Caselets involve conflicting stakeholders: shareholders desiring quarterly profits, factory workers demanding wage hikes, local communities concerned about water runoff, and suppliers struggling with payment terms. Leaders must map leverage, legitimacy, and vulnerability.",
    frameworkSteps: [
      "1. Identify primary stakeholders (those directly impacted: employees, customers, shareholders).",
      "2. Identify secondary stakeholders (regulators, local residents, media, environment).",
      "3. Assess the legitimacy and power of each group's claim.",
      "4. Seek win-win or phased-compromise solutions before choosing zero-sum trade-offs.",
    ],
    decisionRules: [
      "Vulnerable stakeholders without strong bargaining power (e.g. daily wage workers, local ecology) cannot be arbitrarily victimized for short-term corporate expediency.",
      "Fiduciary obligations to institutional investors cannot override statutory safety and consumer welfare.",
      "Transparent multi-party consultation is superior to unilateral executive decrees.",
    ],
    commonTraps: [
      "Prioritizing the loudest stakeholder over the stakeholder with the most legitimate moral or legal claim.",
      "Assuming all stakeholder interests are mutually irreconcilable without testing phased agreements.",
    ],
    xlriPerspective: "A true XLRI manager acts as a trustee for society and organizational sustainability, refusing to exploit asymmetrical power against weaker constituents.",
    caseletExample: {
      situation: "A chemical plant must install an effluent treatment facility costing 15% of annual net profit to prevent river pollution affecting fishermen.",
      trapOption: "Quietly pay local village heads financial compensation to drop their protests while maintaining current effluent discharge.",
      whyTrap: "Bribes intermediaries, leaves environmental poisoning unchecked, and invites catastrophic regulatory penalties.",
      optimalOption: "Commit to phased capital investment for full wastewater recycling, share audit metrics with community representatives, and optimize operational waste to recoup costs.",
      whyOptimal: "Preserves ecological health, maintains legal legitimacy, and aligns community and corporate survival.",
    },
  },
  {
    id: "dm-concept-03",
    number: 3,
    title: "Prioritization",
    corePrinciple: "When time and attention are strictly constrained, sequence actions by criticality of risk, reversibility of decision, and statutory urgency.",
    overview: "Exam candidates frequently encounter crises with multiple simultaneous escalations: an impending media deadline, an unverified safety tip, a disaffected team lead, and an ongoing vendor negotiation. Selecting the correct order of sequence is pivotal.",
    frameworkSteps: [
      "1. Tier 1: Immediate physical safety, human life, and regulatory compliance (non-negotiable).",
      "2. Tier 2: Containment of reputational and financial contamination (information verification).",
      "3. Tier 3: Internal operational stabilization (team reassurances, workflow adjustments).",
      "4. Tier 4: Long-term post-mortem and structural reform.",
    ],
    decisionRules: [
      "Safety and statutory legality always precede commercial convenience and quarterly revenue.",
      "Irreversible decisions (e.g. firing a whistleblower, shutting a facility) should be deferred until essential factual verification is achieved.",
      "Never hold a public press conference before establishing internal factual consensus.",
    ],
    commonTraps: [
      "Rushing to defend public PR before finding out whether the underlying accusation has empirical merit.",
      "Focusing on minor operational squabbles while an existential regulatory inspection is pending.",
    ],
    xlriPerspective: "Prioritization separates high-calibre executives from impulsive fire-fighters. Systematic sequencing prevents panic-induced blunders.",
    caseletExample: {
      situation: "An airline pilot reports abnormal wing vibration during pre-flight checks, while 200 passengers threaten protests if delayed beyond 30 minutes.",
      trapOption: "Clear the flight for departure and instruct the flight crew to monitor vibrations mid-air to prevent passenger wrath.",
      whyTrap: "Trades passenger safety against convenience; violates aviation safety protocol.",
      optimalOption: "Ground the aircraft for an immediate engineering inspection, deplane passengers with complimentary refreshments and clear updates, and arrange a backup craft.",
      whyOptimal: "Unconditionally prioritizes safety while professionally mitigating passenger discomfort.",
    },
  },
  {
    id: "dm-concept-04",
    number: 4,
    title: "Resource Allocation",
    corePrinciple: "Capital, talent, and executive bandwidth are finite. Allocate based on marginal return, strategic alignment, and bottleneck alleviation.",
    overview: "Firms cannot fund every promising project. When choosing between R&D, marketing, talent retention, or debt servicing, managers must weigh opportunity costs and sustainable competitive advantages.",
    frameworkSteps: [
      "1. Quantify available resources (budget, technical headcount, calendar runway).",
      "2. Map each competing project to core organizational objectives.",
      "3. Evaluate downside exposure if a project is underfunded.",
      "4. Allocate to alleviate the primary organizational constraint (Theory of Constraints).",
    ],
    decisionRules: [
      "Avoid spreading resources so thinly across all initiatives that none attain escape velocity ('peanut buttering').",
      "Sunk costs must be ignored; allocate capital based on prospective returns, not historical investment.",
      "Critical maintenance and compliance cannot be starved to finance speculative bets.",
    ],
    commonTraps: [
      "Pouring money into a failing legacy product line out of sentimental attachment rather than funding modern high-growth channels.",
      "Equally dividing a budget among five department heads to avoid difficult political conversations.",
    ],
    xlriPerspective: "Managerial courage is required to make selective bets and defund unviable vanity projects.",
    caseletExample: {
      situation: "An ed-tech startup has 6 months of cash runway. Sales leads are drying up, and the Android app has a 2.8-star rating due to bugs.",
      trapOption: "Split remaining cash equally between high-budget celebrity brand endorsements and international office expansion.",
      whyTrap: "Burns scarce cash without resolving the product quality defect that is driving customers away.",
      optimalOption: "Direct resources toward fixing critical stability bugs, retain senior developers, and run targeted community outreach to existing active users.",
      whyOptimal: "Stabilizes the core product engine to achieve sustainable retention with minimum cash burn.",
    },
  },
  {
    id: "dm-concept-05",
    number: 5,
    title: "Fairness",
    corePrinciple: "Procedural justice and objective equality build organizational trust. Rules must apply universally, regardless of seniority, lineage, or star-performer status.",
    overview: "Scenarios often involve a star salesman who consistently violates anti-harassment policies, or a founder's relative requesting promotion over a diligently performing senior lead. The manager must safeguard institutional integrity.",
    frameworkSteps: [
      "1. Review published organizational code of conduct and policy manuals.",
      "2. Separate the person's performance/status from the standard of conduct required.",
      "3. Ensure the accused receives a neutral hearing with documented evidence.",
      "4. Apply sanctions consistently with past institutional precedents.",
    ],
    decisionRules: [
      "No employee is indispensable enough to justify exempting them from ethical conduct and respectful workplace rules.",
      "Decisions that appear arbitrary or nepotistic destroy morale and trigger talent exodus.",
      "Transparency in evaluation criteria is as vital as the final evaluation outcome.",
    ],
    commonTraps: [
      "Giving a verbal warning off-the-record to a top revenue generator while severely penalizing a junior employee for an identical infraction.",
      "Judging disputes based on personal likability rather than verified facts.",
    ],
    xlriPerspective: "XLRI's founding ethos as an industrial relations institution champions workplace equity and human dignity above expedient favoritism.",
    caseletExample: {
      situation: "The top investment banking producer responsible for 40% of the desk's profits is repeatedly found verbally abusive toward junior analysts.",
      trapOption: "Assign analysts who do not complain to his team and give him a private bonus incentive to tone down his language.",
      whyTrap: "Normalizes abuse, signals that high earners are immune to discipline, and creates legal liability.",
      optimalOption: "Initiate formal HR disciplinary proceedings in accordance with anti-harassment policy, mandate executive coaching, and issue a written final warning.",
      whyOptimal: "Enforces equal standards of dignity across the organization, protecting organizational culture and long-term talent pipeline.",
    },
  },
  {
    id: "dm-concept-06",
    number: 6,
    title: "Ethical Reasoning",
    corePrinciple: "The right decision must pass the tests of universality, transparency, and moral duty. Profit gained through deception or exploitation is illegitimate.",
    overview: "XAT ethics problems rarely pit pure good against cartoonish evil; rather, they present situations where adhering to the highest ethical standard incurs an immediate commercial cost or where regulations contain loopholes.",
    frameworkSteps: [
      "1. Legal vs. Ethical test: Just because an action is not explicitly illegal does not make it ethically permissible.",
      "2. Sunlight test: Would you be comfortable having this decision printed on the front page of a leading national newspaper?",
      "3. Golden rule: How would you view this action if you were the customer, employee, or citizen affected?",
      "4. Categorical Imperative: What if every enterprise in the industry adopted this behavior?",
    ],
    decisionRules: [
      "Exploiting statutory ambiguity or regulatory loopholes to harm consumers or the public interest is categorically unacceptable.",
      "Whistleblowers acting in good faith must be legally and professionally protected.",
      "Falsification of test data or clinical metrics is an instant disqualifier.",
    ],
    commonTraps: [
      "Justifying questionable practices with 'everyone in our industry does this to survive.'",
      "Confusing legality with morality.",
    ],
    xlriPerspective: "Integrity is non-negotiable at XLRI. An option that achieves business profit through moral compromise is always a distractor to be rejected.",
    caseletExample: {
      situation: "A food manufacturer discovers that an unlisted food preservative, legal in export markets but banned locally due to a bureaucratic delay, has been used in 50,000 snack packs.",
      trapOption: "Quietly discount and sell the stock in rural markets where food safety inspections are rare.",
      whyTrap: "Grossly unethical exploitation of vulnerable consumers; high legal and reputational exposure.",
      optimalOption: "Immediately halt distribution, recall distributed batches, notify the food safety regulator, and review quality assurance protocols.",
      whyOptimal: "Upholds consumer safety and brand integrity above short-term inventory write-offs.",
    },
  },
  {
    id: "dm-concept-07",
    number: 7,
    title: "Feasibility",
    corePrinciple: "A theoretically flawless plan that cannot be executed within existing technical, legal, and operational constraints is a failed plan.",
    overview: "Candidates often choose idealistic options that sound noble but require impossible resources—such as retraining 10,000 workers in 48 hours, renegotiating a sovereign trade treaty, or rewriting an entire codebase overnight.",
    frameworkSteps: [
      "1. Check operational feasibility: Does the organization possess the equipment, logistics, and personnel?",
      "2. Check financial feasibility: Is the requisite capital available without insolvency?",
      "3. Check legal and contractual feasibility: Does it violate existing collective bargaining or exclusivity contracts?",
      "4. Check timeline feasibility: Can milestones be realistically attained?",
    ],
    decisionRules: [
      "Select realistic, staged execution over grandiose declarations that lack tangible execution roadmaps.",
      "Ensure the recommended solution accounts for organizational inertia and change management resistance.",
      "Reject options that assume instant, friction-free compliance from all counterparties.",
    ],
    commonTraps: [
      "Selecting an option that commands employees to 'simply work twice as hard with zero errors.'",
      "Proposing immediate termination of a critical monopoly supplier with zero alternative vendors on standby.",
    ],
    xlriPerspective: "Managerial competence requires pragmatic problem-solving grounded in physical reality, not wishful thinking.",
    caseletExample: {
      situation: "A hospital encounters severe nurse burnout and medication charting errors due to an antiquated paper-based record system.",
      trapOption: "Mandate that nurses work unpaid overtime to manually audit records twice daily.",
      whyTrap: "Exacerbates burnout, causes mass resignations, and increases medical error rates.",
      optimalOption: "Deploy a lightweight, phased tablet-based digital charting system with hands-on ward training and hire temporary locum nurses during the transition.",
      whyOptimal: "Pragmatic, manageable intervention that directly solves the operational root cause.",
    },
  },
  {
    id: "dm-concept-08",
    number: 8,
    title: "Short-Term vs Long-Term Impact",
    corePrinciple: "Never sacrifice permanent franchise value and systemic trust for a transient quarterly gain. Structure transitions to survive the present without mortgaging the future.",
    overview: "Pressure from stock analysts or quarterly performance reviews often tempts managers to cut R&D, skimp on safety training, or slash customer support. XAT tests your ability to protect long-term endurance.",
    frameworkSteps: [
      "1. Map immediate consequences (0–6 months) vs. long-term ramifications (2–5 years).",
      "2. Identify whether cost savings represent genuine efficiencies or deferred maintenance.",
      "3. Evaluate brand equity, employee loyalty, and customer goodwill as durable assets.",
      "4. Design bridge solutions that maintain cash solvency while keeping long-term growth engines funded.",
    ],
    decisionRules: [
      "Reject short-term cost cuts that structurally damage customer trust or core engineering capability.",
      "Sustainable growth beats speculative boom-and-bust spikes.",
      "Account for ecological and societal compounding effects.",
    ],
    commonTraps: [
      "Canceling all employee training to meet a quarterly EBITDA target.",
      "Using cheap, toxic packaging that saves 3% per unit but creates long-term environmental litigation.",
    ],
    xlriPerspective: "Stewards build institutions that outlast their tenure. XAT penalizes myopic, mercenary decision-making.",
    caseletExample: {
      situation: "An automotive components supplier is offered a lucrative 3-year contract provided they reduce testing cycles by 50% to expedite deliveries.",
      trapOption: "Accept the contract and reduce testing cycles, trusting that factory defect rates have historically been low.",
      whyTrap: "A single catastrophic vehicle failure due to uninspected parts will destroy the company's tier-1 supplier accreditation.",
      optimalOption: "Decline to reduce testing standards; propose automated computerized test benches that shave cycle times safely, or negotiate a realistic milestone timeline.",
      whyOptimal: "Preserves zero-defect manufacturing integrity and long-term brand credibility.",
    },
  },
  {
    id: "dm-concept-09",
    number: 9,
    title: "Risk Assessment",
    corePrinciple: "Quantify probability and severity of adverse events. Implement mitigation, hedging, and contingency safeguards before pursuing upside.",
    overview: "Risk in Decision Making is not about avoiding all uncertainty—business is inherently about calculated risk. It is about avoiding 'ruin risk' (actions where failure leads to insolvency or criminal liability).",
    frameworkSteps: [
      "1. Identify failure modes: What is the worst-case scenario if this hypothesis fails?",
      "2. Calculate asymmetric payoffs: Is the upside capped while the downside is catastrophic?",
      "3. Establish fail-safes and circuit breakers (e.g. pilot testing before full rollout).",
      "4. Ensure the firm has adequate capital buffers to absorb unexpected shocks.",
    ],
    decisionRules: [
      "Never wager the entire existence of the firm on an unhedged speculative bet.",
      "Run pilot programs and phased canary deployments to validate assumptions at low cost.",
      "Diversify dependencies to avoid single points of catastrophic failure.",
    ],
    commonTraps: [
      "Ignoring low-probability, catastrophic-impact 'Black Swan' vulnerabilities.",
      "Confusing lack of historical evidence of failure with proof of safety.",
    ],
    xlriPerspective: "Fiduciary prudence requires protecting the core while innovating at the margin.",
    caseletExample: {
      situation: "A fintech firm wants to launch an algorithmic lending feature with zero human underwriter oversight.",
      trapOption: "Deploy the algorithm nationwide to all 5 million registered app users to capture market share before competitors.",
      whyTrap: "Massive systemic risk: an untested algorithmic glitch could disburse hundreds of crores in bad loans within hours.",
      optimalOption: "Conduct a closed beta test with 5,000 low-risk customers, set credit ceiling caps, and run weekly human audit reconciliations.",
      whyOptimal: "Enables empirical model validation while strictly bounding downside financial risk.",
    },
  },
  {
    id: "dm-concept-10",
    number: 10,
    title: "Conflict Resolution",
    corePrinciple: "Mediate disputes by uncoupling personalities from objective interests. Find mutual ground on overarching shared goals rather than taking sides emotionally.",
    overview: "Interpersonal and inter-departmental conflicts (e.g. Marketing vs. Production, R&D vs. Finance) paralyze organizations. A manager must de-escalate emotional friction and re-align both parties with collective targets.",
    frameworkSteps: [
      "1. Separate relational friction from substantive task disagreement.",
      "2. Invite both parties into structured dialogue with objective metric baselines.",
      "3. Identify superordinate goals both factions share (e.g. customer retention, company survival).",
      "4. Establish a joint working protocol with clear reciprocal responsibilities.",
    ],
    decisionRules: [
      "Avoid publicly humiliating either party, as this hardens defensiveness and breeds passive aggression.",
      "Do not impose an arbitrary top-down compromise that satisfies neither side and leaves operational friction intact.",
      "Use data and agreed-upon KPIs as the neutral arbiter of disputes.",
    ],
    commonTraps: [
      "Transferring one of the combatants without resolving the cross-functional workflow friction that generated the dispute.",
      "Choosing the side of the more charismatic or senior individual.",
    ],
    xlriPerspective: "Constructive collaboration is essential for organizational cohesion. Managers must be skilled negotiators who build consensus.",
    caseletExample: {
      situation: "The Sales Director wants bespoke product customizations to close corporate accounts, while the Head of Engineering refuses because it creates severe code debt.",
      trapOption: "Order the Engineering team to fulfill all Sales requests unconditionally because revenue is top priority.",
      whyTrap: "Alienates developers, causes technical regressions, and creates an unsustainable product architecture.",
      optimalOption: "Convene a joint weekly triage council to establish a standardized customization tier list, pricing bespoke features appropriately to offset engineering overhead.",
      whyOptimal: "Aligns commercial incentives with architectural stability through shared governance.",
    },
  },
  {
    id: "dm-concept-11",
    number: 11,
    title: "Evidence-Based Decision Making",
    corePrinciple: "Base decisions on empirical data, statistical rigour, and verifiable facts rather than gut feeling, vanity metrics, or ideological dogma.",
    overview: "Caselets often provide conflicting opinions from veteran managers alongside statistical surveys or operational logs. The competent leader interrogates sample sizes, correlation vs. causation, and data integrity.",
    frameworkSteps: [
      "1. Scrutinize data collection methodology: Was the sample representative? Were survey questions biased?",
      "2. Distinguish statistical correlation from causal mechanism.",
      "3. Seek disconfirming evidence rather than cherry-picking data to support a pre-existing bias.",
      "4. When data is contradictory or absent, initiate a targeted fact-finding inquiry before acting.",
    ],
    decisionRules: [
      "Anecdotes and HiPPO (Highest Paid Person's Opinion) cannot override rigorous empirical benchmarks.",
      "Verify the freshness and relevance of data—historical data from pre-crisis periods may be dangerously misleading.",
      "Distinguish between vanity metrics (e.g. app downloads) and engagement metrics (e.g. daily retention, churn).",
    ],
    commonTraps: [
      "Overreacting to a single vocal customer complaint when 99.4% of surveyed customers report high satisfaction.",
      "Assuming a pilot test conducted in an affluent urban pocket will generalize identically to tier-3 towns.",
    ],
    xlriPerspective: "Disciplined inquiry beats emotional intuition. XLRI seeks analytical minds capable of parsing complex, noisy business realities.",
    caseletExample: {
      situation: "A retail pharmacy chain is considering discontinuing its 24-hour service because night electricity costs rose 10%.",
      trapOption: "Shut down night hours immediately based on the store manager's complaint about tiredness.",
      whyTrap: "Fails to analyze net revenue generated by emergency night purchases and brand stickiness.",
      optimalOption: "Analyze hourly transaction records, emergency prescription margins, and customer lifetime value of night shoppers before deciding operational hours.",
      whyOptimal: "Ensures decisions reflect empirical profitability and community healthcare needs.",
    },
  },
  {
    id: "dm-concept-12",
    number: 12,
    title: "Organizational Objectives",
    corePrinciple: "Every tactical choice must directly advance the mission, vision, and core strategic charter of the enterprise while honoring social responsibility.",
    overview: "Tactical fire-fighting often leads companies astray into unrelated diversification or mission creep. Decisions must be evaluated through the prism of the enterprise's true raison d'être.",
    frameworkSteps: [
      "1. Articulate the overarching institutional mission (e.g. low-cost accessibility, premium reliability, cutting-edge innovation).",
      "2. Test whether the proposed option dilutes or reinforces that mission.",
      "3. Evaluate brand positioning and long-term moat defensibility.",
      "4. Align incentive structures across the hierarchy with the stated charter.",
    ],
    decisionRules: [
      "Never pursue a high-margin venture that directly undermines the core identity and trust of your primary brand.",
      "Ensure organizational policies, sales targets, and remuneration packages incentivize the desired mission behaviors.",
      "Mission-driven organizations command higher stakeholder resilience during crises.",
    ],
    commonTraps: [
      "A budget airline offering luxury champagne lounges, inflating operating costs and confusing core price-sensitive travelers.",
      "Prioritizing departmental glory over overall corporate health.",
    ],
    xlriPerspective: "True leaders never lose sight of the North Star. Strategic coherence ensures organizational longevity.",
    caseletExample: {
      situation: "A non-profit hospital founded to provide affordable cardiac surgeries to impoverished rural families is offered private equity funding if it pivots 80% of beds to luxury cosmetic surgery.",
      trapOption: "Accept the deal to maximize short-term cash flows and pay management large bonuses.",
      whyTrap: "Completely betrays the hospital's founding charter and public charitable trust.",
      optimalOption: "Decline the pivot; explore cross-subsidization where a modest 15% private wing subsidizes rural pediatric cardiac care without altering the founding mission.",
      whyOptimal: "Maintains financial viability while rigorously honoring the foundational social purpose.",
    },
  },
];

// ==========================================
// AUTHENTIC XAT DECISION MAKING CASELETS
// ==========================================

export const XAT_DM_CASELETS: DMCaselet[] = [
  // ==========================================
  // CASELET 1: Ethical & Managerial Dilemma
  // ==========================================
  {
    id: "xat-dm-caselet-01",
    exam: "XAT",
    section: "Decision Making",
    title: "The Industrial Effluent Dilemma at GreenPulse Chemicals",
    category: "Ethical Dilemmas",
    difficulty: "XAT_LEVEL",
    scenario: 
      "GreenPulse Chemicals is a mid-sized specialty agrochemical manufacturer operating in the coastal industrial belt of Gujarat. The company employs 850 workers, predominantly from the adjacent fishing hamlet of Navibandhar. GreenPulse's effluent treatment plant (ETP) operates under strict compliance with the State Pollution Control Board's (SPCB) discharge standards established in 2018. However, internal periodic chemical chromatography conducted by Dr. Meenakshi Sundaram, newly hired VP of Quality & Sustainability, reveals trace concentrations of a newly synthesized organophosphate compound, OP-9. While OP-9 is currently unregulated under existing Indian environmental statutes, peer-reviewed international toxicological studies published by the WHO in late 2025 link chronic bioaccumulation of OP-9 in marine estuarine ecosystems to endocrine disruption in fish and potential long-term carcinogenic risks to consumers eating local seafood over a 15-year horizon. Upgrading the existing ETP to install an advanced catalytic oxidation chamber capable of neutralizing OP-9 requires a capital expenditure of ₹18 Crores, accompanied by an ongoing annual operating cost of ₹3.5 Crores. GreenPulse's net annual profit for the preceding fiscal was ₹22 Crores, and the company is currently servicing a ₹40 Crore term loan for an export capacity expansion that promises to create 300 new permanent jobs.",
    background:
      "GreenPulse is facing intense price competition from Chinese chemical exporters who operate with lower environmental overheads. The Managing Director, Mr. Rajesh Shah, is preparing for an Initial Public Offering (IPO) slated for Q3 of the next fiscal year. Any material reduction in operating margins could lower the IPO valuation and jeopardize institutional underwriter commitments.",
    relevantFacts: [
      "Current discharge fully meets all statutory state and national environmental regulations.",
      "Compound OP-9 is unregulated by SPCB, but WHO research links chronic accumulation to carcinogenicity.",
      "Neutralizing OP-9 costs ₹18 Cr upfront + ₹3.5 Cr/year (vs net profit of ₹22 Cr).",
      "850 current employees depend on the plant, with 300 prospective jobs tied to the export loan.",
      "GreenPulse is targeting an IPO in Q3 of next fiscal year.",
      "Navibandhar village relies heavily on the local creek for artisanal fishing.",
    ],
    stakeholders: [
      { name: "Mr. Rajesh Shah", role: "Managing Director", interest: "Maintain profitability, protect IPO valuation, and service debt." },
      { name: "Dr. Meenakshi Sundaram", role: "VP Quality & Sustainability", interest: "Uphold scientific ethics, prevent ecological toxicity and human harm." },
      { name: "Navibandhar Villagers & Fisherfolk", role: "Local Community", interest: "Livelihoods, potable groundwater, safe fish stock." },
      { name: "Factory Workers", role: "Current & Future Employees", interest: "Job security, fair wages, plant continuity." },
      { name: "SPCB & Regulators", role: "Statutory Authority", interest: "Enforce published environmental statutes." },
    ],
    constraints: [
      "Company cannot afford an immediate ₹18 Cr one-shot cash outflow without defaulting on debt covenants.",
      "Ignoring OP-9 creates catastrophic future moral, legal, and brand liabilities.",
      "Unilateral shutdown would render 850 families destitute immediately.",
    ],
    competingInterests: [
      "Immediate financial solvency and IPO valuation vs. long-term ecological and public health stewardship.",
      "Employment generation vs. environmental risk containment.",
    ],
    decisionObjective:
      "Formulate a prudent, ethical, and operationally viable corporate response that addresses the public health risk while preserving the enterprise's financial continuity and stakeholder trust.",
    questions: [
      {
        id: "dm-01-q1",
        caseletId: "xat-dm-caselet-01",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 1,
        difficulty: "XAT_LEVEL",
        conceptTested: "Identifying the Core Problem & Ethical Reasoning",
        questionText: "What is the primary underlying ethical and managerial dilemma confronting the Board of GreenPulse Chemicals?",
        options: [
          { label: "A", text: "Whether to fire Dr. Meenakshi Sundaram for conducting unauthorized chromatography tests that could hurt the upcoming IPO valuation." },
          { label: "B", text: "Whether to prioritize legal minimalism and short-term financial returns over voluntary proactive responsibility toward unpriced ecological and human health risks." },
          { label: "C", text: "Whether to shift all factory operations overseas to circumvent regulatory scrutiny by Indian authorities." },
          { label: "D", text: "Whether to shut down the plant immediately and liquidate assets to pay compensation to the local fisherfolk." },
          { label: "E", text: "Whether to lobby the SPCB to permanently exempt GreenPulse from future environmental standards." },
        ],
        correctAnswer: "B",
        explanation: "The core dilemma is the classic XAT tension between legal compliance (the discharge is not yet statutory illegal) and ethical responsibility (the compound causes demonstrable long-term harm to human health and ecology). Option B accurately frames this fundamental tension.",
        keyReasoning: "A manager must look beyond mere legal compliance to systemic ethical stewardship, weighing financial viability against public safety.",
        validation: {
          feasibility: "Framing the problem as legal minimalism vs proactive stewardship allows a balanced, phased resolution.",
          stakeholderImpact: "Recognizes both the community's health rights and the enterprise's economic duties.",
          fairness: "Treats community welfare as intrinsically valuable, not an externality to be brushed aside.",
          ethicalConsistency: "Aligns with utilitarian and deontological ethics: do no harm.",
          organizationalObjective: "Protects long-term brand equity and sustainable corporate continuity.",
          riskAssessment: "Prevents future catastrophic litigation and criminal liability.",
          longTermConsequences: "Builds a resilient, credible institutional reputation.",
        },
      },
      {
        id: "dm-01-q2",
        caseletId: "xat-dm-caselet-01",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 2,
        difficulty: "XAT_LEVEL",
        conceptTested: "Short-Term vs Long-Term Impact & Feasibility",
        questionText: "Which of the following courses of action should Mr. Rajesh Shah recommend to the Board as the most judicious and responsible strategy?",
        options: [
          { label: "A", text: "Suppress Dr. Sundaram's report, proceed with the IPO without disclosure, and consider upgrading the ETP five years later if Indian regulations mandate it." },
          { label: "B", text: "Shut down manufacturing immediately until the ₹18 Crore upgrade is funded, placing all 850 employees on indefinite unpaid leave." },
          { label: "C", text: "Phase in the catalytic oxidation upgrade over 18 months via a dedicated sustainability green loan, transparently disclose the proactive upgrade in the IPO draft prospectus as an ESG benchmark, and implement temporary batch recirculation to cut OP-9 output by 40% immediately." },
          { label: "D", text: "Quietly pay an annual cash stipend to the village panchayat leaders of Navibandhar on condition that they do not permit soil or water testing by external researchers." },
          { label: "E", text: "Sell the agrochemical manufacturing patent to an unregulated third-party subcontractor and lease back the finished product." },
        ],
        correctAnswer: "C",
        explanation: "Option C provides a balanced, feasible, and ethical solution: it initiates an 18-month phased engineering remediation, finances it via green debt, takes immediate mitigation action (batch recirculation), and turns the transparency into an ESG asset for the IPO. Options A and D are fraudulent/unethical, B causes catastrophic economic ruin, and E is an irresponsible shell game.",
        keyReasoning: "Pragmatic managerial ethics requires finding actionable execution pathways that address the harm without gratuitously destroying the enterprise.",
        validation: {
          feasibility: "Green loans and phased capex over 18 months avoid immediate insolvency.",
          stakeholderImpact: "Protects community health, preserves 850 jobs, and provides institutional investors with transparent governance.",
          fairness: "Addresses the genuine grievance of the local ecosystem fairly.",
          ethicalConsistency: "Full transparency in the IPO prospectus adheres to highest governance standards.",
          organizationalObjective: "Maintains business continuity while modernizing infrastructure.",
          riskAssessment: "Eliminates post-IPO regulatory shock and whistleblower exposure.",
          longTermConsequences: "Positions GreenPulse as an industry-leading sustainable ESG manufacturer.",
        },
      },
      {
        id: "dm-01-q3",
        caseletId: "xat-dm-caselet-01",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 3,
        difficulty: "XAT_LEVEL",
        conceptTested: "Stakeholder Conflict & Prioritization",
        questionText: "If the village elders of Navibandhar learn rumors of the toxic report and threaten an immediate indefinite blockade of the factory gates, what should the management do FIRST?",
        options: [
          { label: "A", text: "Obtain a police injunction and use riot forces to clear the villagers by force to ensure the factory does not lose a single day's production." },
          { label: "B", text: "Invite the village leadership and trusted community representatives to an emergency transparent dialogue, present the verified findings alongside the 18-month remediation roadmap, and announce free monthly potable water supply and health checkups in the interim." },
          { label: "C", text: "Deny all allegations in the local press and threaten to sue the village panchayat for commercial defamation." },
          { label: "D", text: "Offer ₹5 Lakhs cash payments to the vocal protest leaders to get them to disband the crowd." },
          { label: "E", text: "Announce that the factory will permanently relocate to another state within 30 days to teach the village a lesson in lost employment." },
        ],
        correctAnswer: "B",
        explanation: "The first step in crisis de-escalation is transparent engagement, presenting verified facts, sharing the concrete remediation plan, and offering immediate interim relief (clean water and medical camps). Violent force (A), deception (C), bribery (D), and vindictive threats (E) are deeply flawed, unethical, and exacerbate the crisis.",
        keyReasoning: "Dialogue, factual transparency, and immediate tangible interim safeguards de-escalate community hostility and establish authentic partnership.",
        validation: {
          feasibility: "Immediate dialogue and interim water tankers are quickly deployable.",
          stakeholderImpact: "Restores community trust and ensures physical safety for all.",
          fairness: "Treats community concerns with respect and dignity.",
          ethicalConsistency: "Rejects deception and coercion.",
          organizationalObjective: "Secures social license to operate.",
          riskAssessment: "Avoids violent clashes, negative national headlines, and immediate plant vandalization.",
          longTermConsequences: "Transforms a hostile standoff into long-term community goodwill.",
        },
      },
      {
        id: "dm-01-q4",
        caseletId: "xat-dm-caselet-01",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 4,
        difficulty: "XAT_LEVEL",
        conceptTested: "Fairness & Organizational Objectives",
        questionText: "A prominent board member suggests: 'Since Dr. Sundaram's proactive testing created this entire crisis, we should curtail the Quality VP's budget and mandate that all future chemical analysis requires prior approval from the Chief Marketing Officer.' How should the Board evaluate this suggestion?",
        options: [
          { label: "A", text: "Accept it enthusiastically, as marketing executives have a superior understanding of commercial risks than laboratory scientists." },
          { label: "B", text: "Reject it firmly, as subordinating independent quality and scientific audits to commercial expediency destroys institutional risk governance and invites systemic catastrophe." },
          { label: "C", text: "Accept it partially by removing Dr. Sundaram from the VP role but allowing her to continue as a junior lab assistant without decision-making power." },
          { label: "D", text: "Abolish the Quality & Sustainability department entirely to cut operational expenses." },
          { label: "E", text: "Instruct the Chief Marketing Officer to rewrite Dr. Sundaram's research papers to state that OP-9 is completely harmless." },
        ],
        correctAnswer: "B",
        explanation: "Shooting the messenger and subordinating independent science/quality checks to marketing creates catastrophic blind spots (reminiscent of historical corporate disasters like Enron, Boeing 737 Max, or Volkswagen emissions). Independent quality governance must be fiercely protected by the Board.",
        keyReasoning: "A board's fiduciary role is to institutionalize independent checks and balances, not cripple oversight to protect executive comfort.",
        validation: {
          feasibility: "Protecting quality oversight requires only moral and governance resolve.",
          stakeholderImpact: "Protects consumers, employees, and long-term shareholders from hidden risks.",
          fairness: "Rewards scientific integrity instead of penalizing ethical courage.",
          ethicalConsistency: "Upholds corporate truthfulness and fiduciary duty.",
          organizationalObjective: "Prevents existential corporate governance breakdown.",
          riskAssessment: "Ensures risks are surfaced early when they can still be managed.",
          longTermConsequences: "Fosters a high-trust culture of technical excellence and integrity.",
        },
      },
    ],
  },

  // ==========================================
  // CASELET 2: Business Strategy & Resource Allocation
  // ==========================================
  {
    id: "xat-dm-caselet-02",
    exam: "XAT",
    section: "Decision Making",
    title: "Apex Logistics: The Autonomous Delivery Fleet Conundrum",
    category: "Resource Allocation",
    difficulty: "XAT_HARD",
    scenario: 
      "Apex Logistics is an established Indian supply chain aggregator with an annualized delivery volume of 120 million packages across 45 tier-1 and tier-2 cities. Apex relies on an on-demand fleet of 14,000 independent delivery partners (gig-economy riders on two-wheelers). Over the past two years, customer delivery expectations have compressed from 48 hours to 30 minutes, resulting in rider fatigue, rising accident rates (up 28% year-on-year), and delivery partner attrition reaching 65% annually. Apex's Chief Technology Officer, Vikram Chawla, proposes a massive capital investment: partner with an autonomous mobility startup, Robomove, to deploy 2,500 autonomous electric delivery pods across 6 high-density pilot zones in Bengaluru and Hyderabad. The project requires ₹75 Crores upfront. Meanwhile, the Head of Human Operations, Sunita Rao, argues that autonomous robotics in chaotic Indian traffic will face severe regulatory hurdles, vandalism, and pedestrian navigation glitches. She proposes spending ₹45 Crores to overhaul the human rider experience: instituting algorithmic pacing that eliminates punitive speeding penalties, providing comprehensive medical insurance, funding electric two-wheeler lease subsidies, and establishing air-conditioned rest hubs across delivery hubs. Apex has ₹80 Crores in unallocated capital reserves and cannot fund both proposals at full scale.",
    background:
      "A fast-growing venture-backed rival, SwiftPulse, recently raised $100 Million and has begun poaching Apex's most experienced drivers by offering an unconditional 20% wage guarantee. If Apex loses its driver density, service level agreements (SLAs) with anchor e-commerce clients will breach, triggering contractual penalty deductions of ₹4 Crores per month.",
    relevantFacts: [
      "Apex operates 14,000 gig riders; attrition is 65% annually; accident rates rose 28%.",
      "CTO proposal: ₹75 Cr for 2,500 autonomous pods in 6 pilot zones.",
      "Head of Operations proposal: ₹45 Cr for human-centric welfare, pacing algorithms, and EV lease subsidies.",
      "Apex has ₹80 Cr in reserves; cannot fund both at full scale.",
      "Competitor SwiftPulse is aggressively poaching drivers with 20% wage guarantees.",
      "Breaching anchor client SLAs carries ₹4 Cr/month in penalties.",
    ],
    stakeholders: [
      { name: "Executive Leadership", role: "CEO & Board", interest: "Protect market share, prevent SLA penalties, ensure scalable profitability." },
      { name: "14,000 Delivery Riders", role: "Gig Workforce", interest: "Fair earnings, physical safety, dignity, manageable workloads." },
      { name: "CTO & Tech Team", role: "Technology Leadership", interest: "Pioneer future-proof autonomous delivery technology." },
      { name: "Head of Operations", role: "Operational Leadership", interest: "Stabilize current fleet, reduce attrition, enhance operational reliability." },
      { name: "Anchor E-Commerce Clients", role: "Key Customers", interest: "Guaranteed 30-minute delivery SLAs with zero disruptions." },
    ],
    constraints: [
      "Reserve capital is strictly capped at ₹80 Crores.",
      "Indian urban traffic is notoriously unpredictable for autonomous robotics.",
      "Immediate driver defection will collapse delivery capacity within 30–60 days.",
    ],
    competingInterests: [
      "Immediate operational survival and fleet stabilization vs. long-term technological automation.",
      "Human welfare and gig worker retention vs. capital expenditure in robotic automation.",
    ],
    decisionObjective:
      "Design an optimal capital allocation and operational strategy that secures immediate delivery fleet stability and shields against competitor poaching, while intelligently exploring technological innovation without betting the company's survival on unproven autonomy.",
    questions: [
      {
        id: "dm-02-q1",
        caseletId: "xat-dm-caselet-02",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 1,
        difficulty: "XAT_HARD",
        conceptTested: "Prioritization & Resource Allocation",
        questionText: "Given Apex's immediate competitive vulnerability to SwiftPulse, how should the CEO allocate the ₹80 Crore capital reserve?",
        options: [
          { label: "A", text: "Commit the entire ₹75 Crores immediately to autonomous delivery pods, announcing the phased termination of all 14,000 human delivery riders within 6 months." },
          { label: "B", text: "Allocate ₹45 Crores immediately to the Human Operations fleet stabilization and welfare plan, and allocate ₹15 Crores to a focused, smaller-scale autonomous pod pilot in controlled environments (like gated business tech parks), keeping ₹20 Crores as a liquid contingency buffer." },
          { label: "C", text: "Distribute all ₹80 Crores as a one-time cash bonus to the 14,000 riders without changing operational algorithms or addressing accident causes." },
          { label: "D", text: "Use the ₹80 Crores to acquire a rival food delivery app to diversify away from e-commerce delivery." },
          { label: "E", text: "Do not spend any capital; file an anti-competitive lawsuit against SwiftPulse in court to halt their recruitment drive." },
        ],
        correctAnswer: "B",
        explanation: "Option B embodies classic XAT decision-making: it addresses the existential, immediate threat (driver attrition and SLA breach) by funding the human fleet stabilization (₹45 Cr), while prudently hedging future technology with a calibrated, smaller-scale pilot in controlled environments (₹15 Cr), and preserving essential liquidity (₹20 Cr). Option A is suicidal given unproven tech in Indian traffic, C squanders reserves without fixing root issues, and D and E evade the problem entirely.",
        keyReasoning: "Sequence your capital: first fortify the foundational operating engine that generates cash flow, then fund exploratory technological options in bounded, low-risk test beds.",
        validation: {
          feasibility: "Total spend is ₹60 Cr, well within the ₹80 Cr reserve, leaving ₹20 Cr cushion.",
          stakeholderImpact: "Stabilizes 14,000 rider livelihoods, satisfies anchor clients, and gives tech teams a real validation platform.",
          fairness: "Treats human workforce with dignity and respects their contribution to company growth.",
          ethicalConsistency: "Directly combats the 28% surge in rider accidents by overhauling punitive algorithms.",
          organizationalObjective: "Protects anchor client contracts and preserves market leadership.",
          riskAssessment: "Avoids placing an existential bet on unproven robotics in chaotic traffic.",
          longTermConsequences: "Builds a highly loyal driver network while acquiring proprietary autonomy data safely.",
        },
      },
      {
        id: "dm-02-q2",
        caseletId: "xat-dm-caselet-02",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 2,
        difficulty: "XAT_HARD",
        conceptTested: "Identifying the Core Problem & Fairness",
        questionText: "Rider accidents have spiked by 28%. An internal investigation reveals that the dispatch algorithm docks 15% of a rider's daily payout if a delivery exceeds 30 minutes, even during heavy rain or traffic jams. What is the most ethically and operationally sound algorithmic revision?",
        options: [
          { label: "A", text: "Increase the penalty deduction to 25% so that riders learn to navigate faster through traffic shortcuts." },
          { label: "B", text: "Eliminate punitive pay deductions for delivery delays caused by external factors (weather, traffic congestion) and replace them with dynamically adjusted delivery windows and positive safety bonuses for incident-free driving." },
          { label: "C", text: "Require all riders to sign a legal waiver acknowledging that all traffic accidents are 100% their own personal responsibility." },
          { label: "D", text: "Shorten the delivery promise to 15 minutes to stay ahead of SwiftPulse's marketing claims." },
          { label: "E", text: "Disable GPS tracking completely to prevent clients from seeing where riders are delayed." },
        ],
        correctAnswer: "B",
        explanation: "The root cause of reckless driving and accidents is the perverse incentive created by punitive docking of pay for external delays. Replacing punitive deductions with dynamic delivery windows (factoring in rain/traffic) and rewarding safe driving aligns employee safety with customer service. Options A and D increase fatalities, while C is callous and legally dubious.",
        keyReasoning: "When system architecture incentivizes hazardous behavior, redesign the incentive structure rather than blaming individuals.",
        validation: {
          feasibility: "Software algorithm parameter modification can be deployed within days.",
          stakeholderImpact: "Immediately reduces rider fatalities and hospitalizations; enhances customer empathy.",
          fairness: "Riders are not penalized for circumstances beyond human control.",
          ethicalConsistency: "Human life is treated as infinitely more valuable than a 5-minute delivery variance.",
          organizationalObjective: "Drastically reduces driver churn and negative publicity.",
          riskAssessment: "Shields Apex from severe regulatory crackdowns and labor tribunal litigation.",
          longTermConsequences: "Establishes Apex as the employer of choice in the gig economy.",
        },
      },
      {
        id: "dm-02-q3",
        caseletId: "xat-dm-caselet-02",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 3,
        difficulty: "XAT_HARD",
        conceptTested: "Risk Assessment & Feasibility",
        questionText: "During the mini-pilot of autonomous pods in a Bengaluru tech park, local street vendors and auto-rickshaw unions complain that the pods are blocking pedestrian paths and threaten to damage them. What should Apex management do?",
        options: [
          { label: "A", text: "Deploy armed private security guards to accompany every pod and threaten police arrest for anyone approaching the vehicles." },
          { label: "B", text: "Pause the pilot temporarily, meet with local community representatives, demarcate clear dedicated micro-transit paths that do not impede foot traffic or local vendor stalls, and hire local youth as pod route assistants." },
          { label: "C", text: "Ignore the complaints, assuming street vendors have no legal standing to object to technological innovation." },
          { label: "D", text: "Cancel all technology initiatives forever and dismantle the tech team immediately." },
          { label: "E", text: "Operate the pods exclusively in the middle of the night between 2:00 AM and 5:00 AM when pedestrians are asleep." },
        ],
        correctAnswer: "B",
        explanation: "Public technological interventions require community buy-in and shared value. Option B proactively engages stakeholders, redesigns route pathways to prevent obstruction, and creates economic inclusivity by employing local youth as route assistants. Force (A), arrogance (C), overreaction (D), or unviable midnight delivery (E) fail fundamentally.",
        keyReasoning: "Technological innovation succeeds only when it is socially harmonized with the local physical and human ecosystem.",
        validation: {
          feasibility: "Community meetings and pathway adjustments are practical and inexpensive.",
          stakeholderImpact: "Protects local vendors while ensuring pods operate without vandalism.",
          fairness: "Validates legitimate pedestrian and vendor rights to shared public spaces.",
          ethicalConsistency: "Fosters shared prosperity rather than exclusionary tech dominance.",
          organizationalObjective: "Allows technology validation to continue constructively.",
          riskAssessment: "Eliminates asset destruction and public relations backlash.",
          longTermConsequences: "Provides a repeatable community-engagement playbook for future city expansions.",
        },
      },
      {
        id: "dm-02-q4",
        caseletId: "xat-dm-caselet-02",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 4,
        difficulty: "XAT_HARD",
        conceptTested: "Evidence-Based Decision Making",
        questionText: "Three months into the fleet stabilization program, rider attrition drops from 65% to 28%, but delivery costs per package rise by ₹2.40. SwiftPulse, burning venture subsidies, begins advertising: 'Faster than Apex, Guaranteed!' How should Apex respond to this competitor move?",
        options: [
          { label: "A", text: "Immediately revert all safety changes, reinstate punitive delay penalties, and cut rider pay by ₹3 to undercut SwiftPulse on price." },
          { label: "B", text: "Mount a campaign highlighting Apex's 99.1% order fulfillment reliability, zero-accident ethical rider certification, and carbon-neutral EV delivery, while demonstrating to anchor e-commerce clients that competitor cash burn is mathematically unsustainable." },
          { label: "C", text: "Fabricate fake orders on SwiftPulse's app to jam their delivery network and increase their driver frustration." },
          { label: "D", text: "Offer free deliveries to all customers and fund the losses by borrowing ₹100 Crores at high interest." },
          { label: "E", text: "Order riders to match competitor delivery speeds off-the-record without changing published policies." },
        ],
        correctAnswer: "B",
        explanation: "Apex has achieved high operational stability (attrition down to 28%). Competing in a race-to-the-bottom cash burn war against venture-subsidized rivals is suicidal. Instead, Apex should differentiate on reliability, ethics, safety, and institutional sustainability, proving to enterprise clients that their supply chain will not collapse when the competitor's funding dries up.",
        keyReasoning: "Never abandon hard-won structural operational health to react hysterically to an opponent's transient, subsidized marketing bluff.",
        validation: {
          feasibility: "Capitalizes on existing achievements without extra cash burn.",
          stakeholderImpact: "Keeps riders stable, reinforces client trust, and maintains margin discipline.",
          fairness: "Honors the commitment made to the delivery workforce.",
          ethicalConsistency: "Refuses to engage in commercial sabotage (Option C) or deceptive double standards (Option E).",
          organizationalObjective: "Builds a durable, profitable enterprise moat.",
          riskAssessment: "Avoids debt spiral and insolvency.",
          longTermConsequences: "Apex emerges as the resilient market leader when venture subsidies subside.",
        },
      },
    ],
  },

  // ==========================================
  // CASELET 3: Workplace & Academic Governance
  // ==========================================
  {
    id: "xat-dm-caselet-03",
    exam: "XAT",
    section: "Decision Making",
    title: "Academic Integrity vs. Corporate Sponsorship at St. Jude's Institute",
    category: "Workplace Dilemmas",
    difficulty: "XAT_LEVEL",
    scenario: 
      "St. Jude's Institute of Management is an elite business school accredited nationally. Prof. Arvind Raman, a senior professor of Finance, has submitted a rigorous research manuscript to the prestigious Journal of Empirical Economics. The study, based on a two-year econometric analysis of 400 Indian microfinance borrowers, concludes that 'FinTrust Ltd', a leading shadow-banking fintech, charges effective annual percentage rates (APR) exceeding 48% through opaque loan-processing fees and bundled insurance products, disproportionately harming rural women borrowers. FinTrust's founder and CEO, Mr. Harish Goenka, is a distinguished alumnus of St. Jude's and has pledged a ₹25 Crore endowment to construct the 'Goenka School of Financial Innovation' on campus. The foundation stone is scheduled to be laid in three weeks in the presence of state ministers. Mr. Goenka calls the Director of St. Jude's, Dr. Sister Philomena, demanding that Prof. Raman's research publication be withdrawn and that the dataset be placed under institutional non-disclosure. Goenka intimates that if the manuscript is published, he will cancel the ₹25 Crore endowment, withdraw FinTrust from campus placement recruitment (where they recruit 35 graduates annually at high salaries), and resign from the Institute's Governing Council in protest.",
    background:
      "St. Jude's is in the middle of a campus infrastructure upgrade funded partly by anticipated donor endowments. However, the Institute's faculty charter explicitly guarantees academic freedom and grants faculty the sole prerogative over their research dissemination.",
    relevantFacts: [
      "Prof. Raman's research is empirically rigorous and accepted by a top peer-reviewed journal.",
      "FinTrust founder has pledged a ₹25 Crore campus endowment and hires 35 MBA students annually.",
      "FinTrust threatens to cancel the donation, boycott placements, and resign if the paper is published.",
      "The Institute's charter strictly guarantees faculty academic freedom.",
      "The foundation stone ceremony is scheduled in three weeks.",
    ],
    stakeholders: [
      { name: "Dr. Sister Philomena", role: "Institute Director", interest: "Protect institutional integrity, student placements, and infrastructure funding." },
      { name: "Prof. Arvind Raman", role: "Researcher & Faculty", interest: "Uphold academic freedom, public interest, and publication rights." },
      { name: "Mr. Harish Goenka", role: "Donor & FinTrust CEO", interest: "Protect corporate reputation and suppress damaging research." },
      { name: "Current Students", role: "Graduating Batch", interest: "Campus placements, recruitment prospects, institute prestige." },
      { name: "Public & Rural Borrowers", role: "Civil Society", interest: "Truthful knowledge on predatory financial practices." },
    ],
    constraints: [
      "Charter prevents the Director from unilaterally ordering a faculty member to suppress research.",
      "Canceling placements 3 months before graduation would cause severe anxiety among students.",
      "Succumbing to donor extortion permanently destroys the Institute's academic standing and credibility.",
    ],
    competingInterests: [
      "Institutional financial endowment and immediate student placements vs. academic freedom and research integrity.",
    ],
    decisionObjective:
      "Uphold academic freedom and ethical governance without triggering avoidable catastrophe for current graduating students.",
    questions: [
      {
        id: "dm-03-q1",
        caseletId: "xat-dm-caselet-03",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 1,
        difficulty: "XAT_LEVEL",
        conceptTested: "Fairness & Ethical Reasoning",
        questionText: "How should the Director, Dr. Sister Philomena, respond to Mr. Goenka's ultimatum?",
        options: [
          { label: "A", text: "Immediately order Prof. Raman to withdraw the paper, threatening termination of his professorship if he refuses." },
          { label: "B", text: "Affirm St. Jude's unwavering commitment to academic freedom, decline to suppress the peer-reviewed research, but offer FinTrust an open academic forum to publish a formal rebuttal or participate in a symposium on microfinance transparency." },
          { label: "C", text: "Quietly alter Prof. Raman's data file so that FinTrust's name is replaced with a fictitious company before the journal prints it." },
          { label: "D", text: "Accept Goenka's demand, pocket the ₹25 Crore donation, and advise Prof. Raman to publish the paper under a pseudonym on an anonymous blog." },
          { label: "E", text: "Expel all current students who have accepted job offers from FinTrust to show defiance against corporate bullying." },
        ],
        correctAnswer: "B",
        explanation: "An academic institution's foundation rests on truth and intellectual freedom. Caving to financial extortion (A, D) or tampering with scholarly data (C) completely destroys the soul and national accreditation of the school. Offering FinTrust a scholarly platform to present counter-data or dialogue (B) upholds academic freedom with professional dignity.",
        keyReasoning: "Academic integrity cannot be auctioned to the highest bidder; legitimate research must be defended, with scholarly discourse as the only valid response.",
        validation: {
          feasibility: "Maintains clear administrative authority and institutional dignity.",
          stakeholderImpact: "Defends faculty rights and public welfare while offering constructive debate.",
          fairness: "Treats academic discovery with fairness and non-censorship.",
          ethicalConsistency: "Uncompromising rejection of corporate censorship.",
          organizationalObjective: "Protects the university's accreditation and century-long reputational prestige.",
          riskAssessment: "Avoids nationwide academic boycotts and faculty strikes.",
          longTermConsequences: "Establishes St. Jude's as an unshakeable bastion of independent scholarship.",
        },
      },
      {
        id: "dm-03-q2",
        caseletId: "xat-dm-caselet-03",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 2,
        difficulty: "XAT_LEVEL",
        conceptTested: "Prioritization & Risk Assessment",
        questionText: "To mitigate the immediate risk of FinTrust boycotting campus placements and leaving 35 students stranded, what should the Placement Committee do immediately?",
        options: [
          { label: "A", text: "Leak the story to sensationalist tabloid media to publicly shame FinTrust into recruiting." },
          { label: "B", text: "Immediately mobilize the wider alumni network across banking and fintech, organize targeted placement drives with alternative recruiters, and brief students with calm transparency." },
          { label: "C", text: "Force the 35 students to work at St. Jude's library as clerical assistants in lieu of corporate placements." },
          { label: "D", text: "Beg Mr. Goenka for mercy and offer to name the entire campus after him if he hires the 35 students." },
          { label: "E", text: "Advise the 35 students to seek legal action against Prof. Raman for ruining their career opportunities." },
        ],
        correctAnswer: "B",
        explanation: "Proactive contingency planning is essential. By tapping into the broader alumni ecosystem and inviting alternative recruiters, the placement cell protects student careers through managerial resourcefulness rather than blackmail (A), groveling (D), or turning students against faculty (E).",
        keyReasoning: "In a crisis of partner disengagement, rapidly mobilize alternative networks to absorb the shock rather than surrendering institutional core values.",
        validation: {
          feasibility: "Elite business school alumni networks possess immense hiring capacity.",
          stakeholderImpact: "Protects the careers of the graduating cohort without ethical compromise.",
          fairness: "Protects innocent students from becoming collateral damage.",
          ethicalConsistency: "Demonstrates institutional resilience and solidarity.",
          organizationalObjective: "Secures career placement outcomes through merit.",
          riskAssessment: "Mitigates unemployment risk systematically.",
          longTermConsequences: "Deepens broader alumni engagement and institutional autonomy.",
        },
      },
      {
        id: "dm-03-q3",
        caseletId: "xat-dm-caselet-03",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 3,
        difficulty: "XAT_LEVEL",
        conceptTested: "Short-Term vs Long-Term Impact & Conflict Resolution",
        questionText: "Regarding the foundation stone ceremony for the 'Goenka School of Financial Innovation' scheduled in three weeks, what is the most dignified and appropriate course of action for Dr. Philomena?",
        options: [
          { label: "A", text: "Cancel the ceremony quietly, send a polite communication to Mr. Goenka reiterating gratitude for past contributions, and postpone the building project until non-conditional donor funding is secured." },
          { label: "B", text: "Hold a public press conference on the day of the ceremony to publicly denigrate Mr. Goenka in front of the invited state ministers." },
          { label: "C", text: "Proceed with the ceremony, take the first tranche of ₹10 Crores, and then publish the paper the next morning." },
          { label: "D", text: "Lock the campus gates against state ministers and declare an indefinite administrative holiday." },
          { label: "E", text: "Hand over the title deed of the Institute's land to FinTrust as a goodwill gesture." },
        ],
        correctAnswer: "A",
        explanation: "Integrity requires that the Institute not accept money tied to unethical strings. Option A is dignified, professional, and firm: it postpones the ceremony without dramatic theatrics or deceit (Option C is bad faith fraud, Option B is juvenile retaliation).",
        keyReasoning: "Sever compromised partnerships gracefully and calmly without descending into unprofessional hostility or duplicity.",
        validation: {
          feasibility: "Polite administrative postponement is standard protocol.",
          stakeholderImpact: "Spares the institution from public scandal and legal embroilment.",
          fairness: "Respects all parties while drawing a firm ethical line.",
          ethicalConsistency: "Refuses to trade scholarly truth for infrastructure cement.",
          organizationalObjective: "Preserves the moral authority of the leadership.",
          riskAssessment: "Avoids immediate media circus and reputational tarring.",
          longTermConsequences: "Attracts high-integrity donors who respect the school's incorruptible standards.",
        },
      },
      {
        id: "dm-03-q4",
        caseletId: "xat-dm-caselet-03",
        exam: "XAT",
        section: "Decision Making",
        questionNumber: 4,
        difficulty: "XAT_LEVEL",
        conceptTested: "Organizational Objectives & Stakeholder Analysis",
        questionText: "Looking forward, what structural policy should the Governing Council of St. Jude's enact to prevent such vulnerabilities from recurring?",
        options: [
          { label: "A", text: "Ban all faculty from conducting research on any corporation that hires St. Jude's graduates or donates funds." },
          { label: "B", text: "Establish an independent 'Academic Endowment & Ethics Charter' specifying that all philanthropic gifts are strictly irrevocable and convey zero governance over curriculum, faculty research, or academic publication." },
          { label: "C", text: "Require all donors to become full-time voting members of the research ethics review board." },
          { label: "D", text: "Cease accepting all corporate donations and double student tuition fees to fund all future infrastructure." },
          { label: "E", text: "Mandate that all faculty papers be reviewed and approved by the Student Placement Council prior to journal submission." },
        ],
        correctAnswer: "B",
        explanation: "Institutional governance must structurally decouple philanthropy from academic oversight. Option B mirrors global best practices (like Harvard or Oxford endowment charters), ensuring gifts are unconditional and non-revocable. Options A, C, and E destroy academic independence, while D creates an unviable burden on students.",
        keyReasoning: "Fix systemic vulnerabilities through robust, published constitutional governance that permanently insulates the core mission from outside leverage.",
        validation: {
          feasibility: "Can be drafted and ratified by the Board of Governors.",
          stakeholderImpact: "Protects faculty, students, and future ethical donors.",
          fairness: "Establishes a uniform, transparent standard for all future philanthropists.",
          ethicalConsistency: "Solidifies institutional independence into binding law.",
          organizationalObjective: "Guarantees that St. Jude's maintains its world-class academic credibility.",
          riskAssessment: "Prevents future donor extortion crises entirely.",
          longTermConsequences: "Attracts prestigious global research grants and world-class faculty.",
        },
      },
    ],
  },
];
