import { StaticGKQuestion, CurrentAffairsQuestion, GKRevisionCard } from "./types";

// ==========================================
// 1. STATIC GK QUESTION BANK (XAT-ONLY)
// ==========================================

export const XAT_STATIC_GK_QUESTIONS: StaticGKQuestion[] = [
  // Indian Polity & Constitution
  {
    id: "xat-gk-static-01",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Constitution",
    subcategory: "Fundamental Rights & Writs",
    question: "Under the Constitution of India, which extraordinary writ is issued by the Supreme Court or High Courts to command a public official or statutory authority to perform a mandatory public duty that they have refused to execute?",
    options: [
      { label: "A", text: "Habeas Corpus" },
      { label: "B", text: "Mandamus" },
      { label: "C", text: "Quo-Warranto" },
      { label: "D", text: "Certiorari" },
      { label: "E", text: "Prohibition" },
    ],
    correctAnswer: "B",
    explanation: "The writ of Mandamus (literally 'We Command') is an order issued by a superior court to any government, court, corporation, or public authority to perform a specific act that falls under their mandatory public duty. Habeas Corpus secures bodily release; Quo-Warranto challenges title to public office; Certiorari quashes lower court orders; Prohibition halts lower tribunal proceedings.",
    importantFact: "Article 32 empowers the Supreme Court and Article 226 empowers High Courts to issue these five prerogative constitutional writs.",
    difficulty: "MEDIUM",
    tags: ["Constitution", "Fundamental Rights", "Writs", "Judiciary"],
  },
  {
    id: "xat-gk-static-02",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Economics",
    subcategory: "Macroeconomics & Monetary Policy",
    question: "In macroeconomic theory, the Phillips Curve postulates an inverse historical relationship between which of the following two macroeconomic variables?",
    options: [
      { label: "A", text: "Fiscal Deficit and Current Account Deficit" },
      { label: "B", text: "Rate of Inflation and Rate of Unemployment" },
      { label: "C", text: "Gross Domestic Product and Income Inequality" },
      { label: "D", text: "Foreign Direct Investment and Foreign Exchange Reserves" },
      { label: "E", text: "Repo Rate and Marginal Standing Facility Rate" },
    ],
    correctAnswer: "B",
    explanation: "Formulated by A.W. Phillips in 1958, the original Phillips Curve demonstrates an inverse trade-off between inflation and unemployment in the short run: lower unemployment typically coincides with higher inflation due to wage pressures, though stagflation challenged the long-run stability of this curve.",
    importantFact: "Milton Friedman and Edmund Phelps later proved that in the long run, the Phillips Curve is vertical at the Natural Rate of Unemployment (NAIRU).",
    difficulty: "MEDIUM",
    tags: ["Economics", "Monetary Theory", "Inflation", "Unemployment"],
  },
  {
    id: "xat-gk-static-03",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Business & Corporate Knowledge",
    subcategory: "Corporate History & Brands",
    question: "Which Indian business conglomerate traces its origins to the Empress Mills textile factory established in Nagpur in 1877 by legendary industrialist Jamsetji Nusserwanji Tata?",
    options: [
      { label: "A", text: "Birla Group" },
      { label: "B", text: "Tata Group" },
      { label: "C", text: "Godrej Group" },
      { label: "D", text: "Wadia Group" },
      { label: "E", text: "Singhania Group" },
    ],
    correctAnswer: "B",
    explanation: "Jamsetji Nusserwanji Tata founded the Central India Spinning, Weaving and Manufacturing Company (famously known as Empress Mills) in Nagpur on 1 January 1877, coinciding with Queen Victoria's proclamation as Empress of India. It laid the industrial foundation of the Tata Group.",
    importantFact: "Empress Mills pioneered modern employee welfare in India, introducing provident funds, medical pensions, and workplace air-cooling decades before statutory labor laws were enacted.",
    difficulty: "EASY",
    tags: ["Business History", "Tata Group", "Industrialization", "Nagpur"],
  },
  {
    id: "xat-gk-static-04",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "World Geography",
    subcategory: "Strategic Maritime Straits",
    question: "The Strait of Malacca, one of the world's most critical maritime shipping chokepoints through which roughly a quarter of global seaborne oil shipments transit, connects which two major bodies of water?",
    options: [
      { label: "A", text: "Red Sea and the Gulf of Aden" },
      { label: "B", text: "Andaman Sea (Indian Ocean) and the South China Sea (Pacific Ocean)" },
      { label: "C", text: "Persian Gulf and the Gulf of Oman" },
      { label: "D", text: "Mediterranean Sea and the Atlantic Ocean" },
      { label: "E", text: "Black Sea and the Sea of Marmara" },
    ],
    correctAnswer: "B",
    explanation: "The Strait of Malacca is a narrow 890-kilometer stretch of water between the Malay Peninsula and the Indonesian island of Sumatra, linking the Indian Ocean (via the Andaman Sea) directly to the Pacific Ocean (via the South China Sea).",
    importantFact: "Over 94,000 vessels traverse the Strait of Malacca annually, making it the premier energy supply corridor for China, Japan, and South Korea.",
    difficulty: "MEDIUM",
    tags: ["Geography", "Maritime Chokepoints", "Straits", "Global Trade"],
  },
  {
    id: "xat-gk-static-05",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "International Institutions",
    subcategory: "Multilateral Treaties & Bretton Woods",
    question: "The historic Bretton Woods Conference held in New Hampshire in July 1944 laid the foundational institutional framework for which two international financial organizations?",
    options: [
      { label: "A", text: "World Trade Organization (WTO) and United Nations Development Programme (UNDP)" },
      { label: "B", text: "International Monetary Fund (IMF) and the International Bank for Reconstruction and Development (IBRD / World Bank)" },
      { label: "C", text: "Bank for International Settlements (BIS) and Organization for Economic Co-operation and Development (OECD)" },
      { label: "D", text: "Asian Development Bank (ADB) and New Development Bank (NDB)" },
      { label: "E", text: "World Economic Forum (WEF) and International Finance Corporation (IFC)" },
    ],
    correctAnswer: "B",
    explanation: "Delegates from 44 nations convened at the Mount Washington Hotel in Bretton Woods, New Hampshire, creating the IMF (to oversee exchange rates and balance of payments stability) and the IBRD (now part of the World Bank Group, to finance post-war reconstruction).",
    importantFact: "John Maynard Keynes (representing the United Kingdom) and Harry Dexter White (representing the United States) were the chief architects of the Bretton Woods system.",
    difficulty: "MEDIUM",
    tags: ["International Institutions", "IMF", "World Bank", "Bretton Woods"],
  },
  {
    id: "xat-gk-static-06",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Indian History",
    subcategory: "Modern History & Freedom Struggle",
    question: "During the Indian freedom struggle, which momentous resolution was formally adopted at the Lahore Session of the Indian National Congress in December 1929 under the presidency of Jawaharlal Nehru?",
    options: [
      { label: "A", text: "Quit India Resolution" },
      { label: "B", text: "Purna Swaraj (Declaration of Complete Independence)" },
      { label: "C", text: "Non-Cooperation Movement Resolution" },
      { label: "D", text: "Civil Disobedience Suspension Resolution" },
      { label: "E", text: "Fundamental Rights and Economic Policy Resolution" },
    ],
    correctAnswer: "B",
    explanation: "At the Lahore Session on 19 December 1929, the Congress promulgated the historic 'Purna Swaraj' resolution, declaring complete independence from British colonial rule as its sole objective. 26 January 1930 was designated as the first Independence Day.",
    importantFact: "To commemorate the 1930 Purna Swaraj declaration, 26 January was specifically chosen as the date for the Indian Constitution to take effect in 1950, celebrated as Republic Day.",
    difficulty: "MEDIUM",
    tags: ["Indian History", "Lahore Session", "Purna Swaraj", "Nehru"],
  },
  {
    id: "xat-gk-static-07",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Environment",
    subcategory: "Biodiversity & Ecology",
    question: "Which international treaty, negotiated under the aegis of UNEP in 1987, is universally acclaimed as the single most successful multilateral environmental agreement for effectively phasing out chlorofluorocarbons (CFCs) and healing the stratospheric ozone layer?",
    options: [
      { label: "A", text: "Kyoto Protocol" },
      { label: "B", text: "Montreal Protocol" },
      { label: "C", text: "Paris Agreement" },
      { label: "D", text: "Basel Convention" },
      { label: "E", text: "Ramsar Convention" },
    ],
    correctAnswer: "B",
    explanation: "The Montreal Protocol on Substances that Deplete the Ozone Layer (adopted in 1987) achieved universal ratification and mandated the global phase-out of ozone-depleting substances including CFCs, halons, and carbon tetrachloride.",
    importantFact: "The 2016 Kigali Amendment to the Montreal Protocol further committed member nations to phase down hydrofluorocarbons (HFCs), potent greenhouse gases.",
    difficulty: "EASY",
    tags: ["Environment", "Montreal Protocol", "Ozone Layer", "Kigali Amendment"],
  },
  {
    id: "xat-gk-static-08",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Science",
    subcategory: "Fundamental Physics & Nobel Laureates",
    question: "Sir C.V. Raman received the Nobel Prize in Physics in 1930 for the discovery of the Raman Effect. What physical phenomenon does the Raman Effect fundamentally describe?",
    options: [
      { label: "A", text: "Emission of electrons when electromagnetic radiation impinges on metallic surfaces" },
      { label: "B", text: "Inelastic scattering of photons by molecules resulting in shifts in wavelength" },
      { label: "C", text: "Splitting of spectral lines in the presence of a strong magnetic field" },
      { label: "D", text: "Total internal reflection of light inside an optical waveguide" },
      { label: "E", text: "Spontaneous emission of coherent microwave radiation" },
    ],
    correctAnswer: "B",
    explanation: "The Raman Effect occurs when a beam of light traverses a transparent chemical substance and a minute fraction of the scattered light emerges with different wavelengths (inelastic scattering), revealing the vibrational energy levels of the molecules.",
    importantFact: "National Science Day is celebrated in India every year on 28 February to commemorate C.V. Raman's discovery of the Raman Effect in 1928.",
    difficulty: "HARD",
    tags: ["Science", "Physics", "Nobel Prize", "C.V. Raman", "Optics"],
  },
  {
    id: "xat-gk-static-09",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Awards",
    subcategory: "Literature & Global Honors",
    question: "Who was the first non-European and first Asian Nobel Laureate, honored with the Nobel Prize in Literature in 1913 for the profound spiritual sensitivity of 'Gitanjali'?",
    options: [
      { label: "A", text: "Yasunari Kawabata" },
      { label: "B", text: "Rabindranath Tagore" },
      { label: "C", text: "Kenzaburo Oe" },
      { label: "D", text: "Mulk Raj Anand" },
      { label: "E", text: "Sri Aurobindo" },
    ],
    correctAnswer: "B",
    explanation: "Rabindranath Tagore was awarded the Nobel Prize in Literature in 1913 'because of his profoundly sensitive, fresh and beautiful verse, by which, with consummate skill, he has made his poetic thought, expressed in his own English words, a part of the literature of the West.'",
    importantFact: "Tagore composed the national anthems for two sovereign nations: 'Jana Gana Mana' (India) and 'Amar Shonar Bangla' (Bangladesh).",
    difficulty: "EASY",
    tags: ["Awards", "Nobel Prize", "Rabindranath Tagore", "Literature"],
  },
  {
    id: "xat-gk-static-10",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: false,
    category: "Important Organizations",
    subcategory: "Central Banking & Regulatory Framework",
    question: "The Reserve Bank of India (RBI) was formally established on April 1, 1935, based upon the structural recommendations of which royal commission?",
    options: [
      { label: "A", text: "Hunter Commission" },
      { label: "B", text: "Hilton Young Commission" },
      { label: "C", text: "Simon Commission" },
      { label: "D", text: "Sarkaria Commission" },
      { label: "E", text: "Kothari Commission" },
    ],
    correctAnswer: "B",
    explanation: "The Royal Commission on Indian Currency and Finance (popularly known as the Hilton Young Commission, 1926) recommended the creation of a central bank to separate the control of currency and credit from the Government, leading to the enactment of the RBI Act of 1934.",
    importantFact: "Dr. B.R. Ambedkar's book 'The Problem of the Rupee: Its Origin and Its Solution' was heavily referenced by the Hilton Young Commission in defining the RBI's architecture.",
    difficulty: "MEDIUM",
    tags: ["Banking", "RBI", "Hilton Young Commission", "Economy"],
  },
];

// ==========================================
// 2. CURRENT AFFAIRS QUESTION BANK (DATE-AWARE, XAT-ONLY)
// ==========================================

export const XAT_CURRENT_AFFAIRS_QUESTIONS: CurrentAffairsQuestion[] = [
  {
    id: "xat-gk-ca-01",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Banking & Finance",
    subcategory: "Central Bank Digital Currency & Cross-Border Payments",
    eventDate: "2026-02-18",
    source: "Reserve Bank of India Monetary Policy & NPCI International Press Bulletin",
    sourceDate: "2026-02-19",
    timeFilterWindow: "30_DAYS",
    year: 2026,
    question: "In early 2026, the Reserve Bank of India, in coordination with NPCI International, achieved a landmark integration enabling real-time cross-border linkage between India's Unified Payments Interface (UPI) and the domestic instant payment networks of which Southeast Asian economic bloc member state?",
    options: [
      { label: "A", text: "Philippines (InstaPay)" },
      { label: "B", text: "Malaysia (DuitNow)" },
      { label: "C", text: "Brunei (FastPay)" },
      { label: "D", text: "Vietnam (Napas)" },
      { label: "E", text: "Cambodia (Bakong)" },
    ],
    correctAnswer: "B",
    explanation: "Following the pioneering UPI-PayNow linkage with Singapore, India operationalized bilateral person-to-person (P2P) and merchant remittances with Malaysia's DuitNow platform, dramatically reducing cross-border transfer transaction fees to under 1.5%.",
    importantFact: "Over 2.8 million Indian diaspora residents in Malaysia can now send low-cost remittances directly from bank accounts in real time.",
    difficulty: "MEDIUM",
    tags: ["UPI", "NPCI", "Malaysia", "DuitNow", "Fintech", "Cross-Border Payments"],
  },
  {
    id: "xat-gk-ca-02",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Economy",
    subcategory: "Union Budget & Fiscal Policy",
    eventDate: "2026-02-01",
    source: "Ministry of Finance, Government of India - Union Budget Presentation",
    sourceDate: "2026-02-01",
    timeFilterWindow: "30_DAYS",
    year: 2026,
    question: "In the Union Budget 2026–27 presented by the Union Finance Minister, what fiscal deficit target relative to Gross Domestic Product (GDP) was targeted for the fiscal year 2026–27 in adherence to the post-pandemic fiscal consolidation glide path?",
    options: [
      { label: "A", text: "5.8% of GDP" },
      { label: "B", text: "4.3% of GDP" },
      { label: "C", text: "3.5% of GDP" },
      { label: "D", text: "6.2% of GDP" },
      { label: "E", text: "4.9% of GDP" },
    ],
    correctAnswer: "B",
    explanation: "The Government of India reaffirmed its commitment to the fiscal consolidation path, aiming to bring down the central fiscal deficit below 4.5% of GDP by FY 2026–27, formally penciling in a 4.3% deficit target backed by robust corporate tax buoyancy and rationalized capital outlays.",
    importantFact: "Effective capital expenditure outlay (Capex) was maintained at a historic high of over ₹11.5 Lakh Crores to sustain national infrastructure asset creation.",
    difficulty: "MEDIUM",
    tags: ["Union Budget 2026", "Fiscal Deficit", "GDP", "Indian Economy"],
  },
  {
    id: "xat-gk-ca-03",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Science",
    subcategory: "Space Exploration & ISRO Missions",
    eventDate: "2025-12-14",
    source: "Indian Space Research Organisation (ISRO) Official Mission Dispatch",
    sourceDate: "2025-12-15",
    timeFilterWindow: "3_MONTHS",
    year: 2025,
    question: "ISRO successfully conducted the integrated uncrewed orbital test flight 'Gaganyaan G-1' utilizing which heavy-lift launch vehicle configuration, paving the way for India's upcoming crewed human spaceflight mission?",
    options: [
      { label: "A", text: "PSLV-XL (Polar Satellite Launch Vehicle)" },
      { label: "B", text: "LVM3-G (Launch Vehicle Mark-3 Human-Rated)" },
      { label: "C", text: "SSLV-D2 (Small Satellite Launch Vehicle)" },
      { label: "D", text: "GSLV Mk II with Cryogenic Upper Stage" },
      { label: "E", text: "RLV-TD (Reusable Launch Vehicle)" },
    ],
    correctAnswer: "B",
    explanation: "ISRO human-rated its heaviest workhorse rocket, the LVM3 (formerly GSLV Mk III), creating the LVM3-G configuration with upgraded Vikas engines and redundant avionics to launch the Gaganyaan orbital module into a 400-km low Earth orbit.",
    importantFact: "The G-1 test mission featured the female-looking humanoid robot 'Vyommitra' installed in the crew capsule to monitor life-support environmental parameters.",
    difficulty: "MEDIUM",
    tags: ["ISRO", "Gaganyaan", "LVM3", "Space Technology", "Vyommitra"],
  },
  {
    id: "xat-gk-ca-04",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Corporate Developments",
    subcategory: "Semiconductor Ecosystem & Industrial Investments",
    eventDate: "2025-11-20",
    source: "Ministry of Electronics and Information Technology (MeitY) & Tata Electronics",
    sourceDate: "2025-11-21",
    timeFilterWindow: "6_MONTHS",
    year: 2025,
    question: "Under the India Semiconductor Mission (ISM), Tata Electronics partnered with which premier global semiconductor wafer foundry to construct India's first commercial ₹91,000 Crore AI chip fabrication plant in Dholera, Gujarat?",
    options: [
      { label: "A", text: "Taiwan Semiconductor Manufacturing Company (TSMC)" },
      { label: "B", text: "Powerchip Semiconductor Manufacturing Corporation (PSMC)" },
      { label: "C", text: "GlobalFoundries" },
      { label: "D", text: "Samsung Foundry" },
      { label: "E", text: "United Microelectronics Corporation (UMC)" },
    ],
    correctAnswer: "B",
    explanation: "Tata Electronics tied up with Taiwan's Powerchip Semiconductor Manufacturing Corporation (PSMC) as its strategic technology partner for the 28nm/55nm Dholera fab, designed with a capacity of 50,000 wafer starts per month across automotive, telecom, and computing sectors.",
    importantFact: "Simultaneously, Tata announced a ₹27,000 Crore semiconductor assembly and test (OSAT) facility in Jagiroad, Morigaon district, Assam.",
    difficulty: "HARD",
    tags: ["Semiconductors", "Tata Electronics", "PSMC", "Dholera", "Make in India"],
  },
  {
    id: "xat-gk-ca-05",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "International Affairs",
    subcategory: "Multilateral Summits & Geopolitics",
    eventDate: "2025-11-18",
    source: "G20 Secretariat & Ministry of External Affairs Communique",
    sourceDate: "2025-11-19",
    timeFilterWindow: "6_MONTHS",
    year: 2025,
    question: "The 20th G20 Leaders' Summit in late 2025 was officially hosted by which country, marking the final year of the continuous Global South troika leadership (Indonesia, India, Brazil, and this host nation)?",
    options: [
      { label: "A", text: "South Africa" },
      { label: "B", text: "Saudi Arabia" },
      { label: "C", text: "Mexico" },
      { label: "D", text: "Argentina" },
      { label: "E", text: "South Korea" },
    ],
    correctAnswer: "A",
    explanation: "South Africa assumed the G20 Presidency for 2025, culminating in the Johannesburg Summit. This completed the four-year cycle of emerging economy leadership across Indonesia (2022), India (2023), Brazil (2024), and South Africa (2025).",
    importantFact: "The South African Presidency championed the integration of the African Union as a full permanent member of the G20, which was formalized under India's 2023 New Delhi Declaration.",
    difficulty: "MEDIUM",
    tags: ["G20", "South Africa", "Global South", "Diplomacy"],
  },
  {
    id: "xat-gk-ca-06",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Important Appointments",
    subcategory: "Global Financial Institutions",
    eventDate: "2025-09-12",
    source: "International Monetary Fund & World Bank Group Press Releases",
    sourceDate: "2025-09-13",
    timeFilterWindow: "12_MONTHS",
    year: 2025,
    question: "Who among the following Indian-origin leaders continues to serve as the 14th President of the World Bank Group, having championed institutional climate finance reforms and private capital mobilization?",
    options: [
      { label: "A", text: "Gita Gopinath" },
      { label: "B", text: "Ajay Banga" },
      { label: "C", text: "Raghuram Rajan" },
      { label: "D", text: "Arvind Subramanian" },
      { label: "E", text: "Soumya Swaminathan" },
    ],
    correctAnswer: "B",
    explanation: "Ajay Banga, former CEO of Mastercard and IIM Ahmedabad alumnus, is the President of the World Bank Group. Under his tenure, the World Bank expanded its core mission statement to: 'To create a world free of poverty on a livable planet.'",
    importantFact: "Ajay Banga is the first Indian-American and first Sikh leader to head the World Bank since its inception in 1944.",
    difficulty: "EASY",
    tags: ["World Bank", "Ajay Banga", "Appointments", "Climate Finance"],
  },
  {
    id: "xat-gk-ca-07",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Sports",
    subcategory: "Olympic Games & Global Tournaments",
    eventDate: "2025-10-04",
    source: "International Olympic Committee (IOC) Executive Board Decision",
    sourceDate: "2025-10-05",
    timeFilterWindow: "12_MONTHS",
    year: 2025,
    question: "Which globally popular sport, having last featured at the Olympic Games in Paris in 1900, is officially confirmed to make its historic Olympic return in T20 format at the Los Angeles 2028 Olympic Games (LA28)?",
    options: [
      { label: "A", text: "Polo" },
      { label: "B", text: "Cricket" },
      { label: "C", text: "Squash" },
      { label: "D", text: "Lacrosse" },
      { label: "E", text: "Baseball" },
    ],
    correctAnswer: "B",
    explanation: "Cricket (specifically the men's and women's six-team Twenty20 format) was officially ratified by the IOC for inclusion in the 2028 Los Angeles Olympics, returning to the Olympic fold after an absence of 128 years.",
    importantFact: "The LA28 sports program also approved Squash, Baseball/Softball, Flag Football, and Lacrosse (Sixes).",
    difficulty: "EASY",
    tags: ["Olympics", "Cricket", "LA28", "IOC", "Sports"],
  },
  {
    id: "xat-gk-ca-08",
    exam: "XAT",
    section: "General Knowledge",
    isCurrentAffairs: true,
    category: "Awards & Honors",
    subcategory: "Nobel Prizes 2025",
    eventDate: "2025-10-10",
    source: "The Royal Swedish Academy of Sciences / Nobel Foundation",
    sourceDate: "2025-10-11",
    timeFilterWindow: "12_MONTHS",
    year: 2025,
    question: "The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel (Nobel Economics Prize) 2024/2025 celebrated breakthrough empirical research on which of the following vital socioeconomic domains?",
    options: [
      { label: "A", text: "Algorithmic game theory and high-frequency auction design" },
      { label: "B", text: "How institutions are formed and how inclusive political and economic institutions drive national prosperity" },
      { label: "C", text: "Cryptocurrency tokenomics and decentralized banking liquidity" },
      { label: "D", text: "Carbon credit pricing elasticity in tropical developing economies" },
      { label: "E", text: "Behavioral nudges for mandatory retirement pension subscriptions" },
    ],
    correctAnswer: "B",
    explanation: "Daron Acemoglu, Simon Johnson, and James A. Robinson were awarded the Nobel Prize in Economic Sciences 'for studies of how institutions are formed and affect prosperity,' demonstrating that inclusive societal institutions foster long-term democracy and economic growth.",
    importantFact: "Acemoglu and Robinson co-authored the internationally acclaimed bestselling book 'Why Nations Fail: The Origins of Power, Prosperity, and Poverty.'",
    difficulty: "HARD",
    tags: ["Nobel Prize", "Economics", "Daron Acemoglu", "Institutions", "Why Nations Fail"],
  },
];

// Combine all GK questions into a master verified XAT pool
export const ALL_XAT_GK_QUESTIONS = [
  ...XAT_STATIC_GK_QUESTIONS,
  ...XAT_CURRENT_AFFAIRS_QUESTIONS,
];

// ==========================================
// 3. XAT GK REVISION FLASHCARDS
// ==========================================

export const XAT_GK_REVISION_CARDS: GKRevisionCard[] = [
  {
    id: "rev-01",
    title: "Article 32 & Constitutional Writs",
    category: "Polity & Constitution",
    isCurrentAffairs: false,
    oneLineFact: "Dr. B.R. Ambedkar termed Article 32 the 'Heart and Soul' of the Constitution.",
    context: "Empowers citizens to move the Supreme Court directly for the enforcement of Fundamental Rights via five writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, and Quo-Warranto.",
    examRelevance: "Frequently tested in XAT every 2 years; focus on distinguishing Mandamus from Quo-Warranto.",
    frequentlyTestedArea: "Constitutional Remedies & Writs",
  },
  {
    id: "rev-02",
    title: "RBI Monetary Policy Transmission & Liquidity Tools",
    category: "Economy & Banking",
    isCurrentAffairs: false,
    oneLineFact: "Standing Deposit Facility (SDF) absorbs liquidity at a rate 25 bps lower than Repo Rate without requiring collateral.",
    context: "Introduced in 2022 to replace reverse repo as the primary floor of the Liquidity Adjustment Facility (LAF) corridor, strengthening liquidity management.",
    examRelevance: "XLRI frequently asks technical central bank policy corridor questions.",
    frequentlyTestedArea: "Monetary Policy Corridor (Repo, SDF, MSF)",
  },
  {
    id: "rev-03",
    title: "India Semiconductor Mission & Dholera Fab",
    category: "Corporate & Tech",
    isCurrentAffairs: true,
    dateOrEra: "2025–2026",
    oneLineFact: "Tata Electronics & Taiwan's PSMC are establishing India's first ₹91,000 Cr commercial chip fab in Dholera.",
    context: "Government of India provides up to 50% fiscal support on capital expenditure for setting up silicon fabs and display fabrication facilities.",
    examRelevance: "High probability for industrial policy and business current affairs.",
    frequentlyTestedArea: "Industrial Investments & High-Tech Manufacturing",
  },
  {
    id: "rev-04",
    title: "Gaganyaan Orbital Test & Vyommitra",
    category: "Science & Tech",
    isCurrentAffairs: true,
    dateOrEra: "2025–2026",
    oneLineFact: "ISRO's human-rated LVM3-G rocket carries the humanoid robot Vyommitra for uncrewed orbital qualification.",
    context: "Prepares India to become the fourth nation (after USSR/Russia, USA, and China) to autonomously launch humans into low Earth orbit.",
    examRelevance: "Space science missions are a permanent staple of XAT GK.",
    frequentlyTestedArea: "Indian Space Missions & Launch Vehicles",
  },
  {
    id: "rev-05",
    title: "Bretton Woods Twins (1944)",
    category: "International Institutions",
    isCurrentAffairs: false,
    oneLineFact: "IMF focuses on balance of payments & exchange rate stability; World Bank finances long-term development projects.",
    context: "Both institutions are headquartered in Washington, D.C. World Bank is traditionally headed by an American nominee; IMF by a European nominee.",
    examRelevance: "Frequently tested under global multilateral financial architecture.",
    frequentlyTestedArea: "Multilateral Economic Institutions",
  },
  {
    id: "rev-06",
    title: "Acemoglu-Robinson Institutional Economics Nobel",
    category: "Awards & Economy",
    isCurrentAffairs: true,
    dateOrEra: "2024–2025",
    oneLineFact: "Inclusive institutions drive long-term prosperity, while extractive institutions perpetuate poverty cycles.",
    context: "Based on empirical natural experiments comparing colonial settler mortality rates and modern GDP per capita.",
    examRelevance: "XAT loves Nobel Economics questions linked to institutional design.",
    frequentlyTestedArea: "Nobel Laureates & Economic Theory",
  },
];
