import { DILRDifficulty, DILRQuestion, DILRSet } from "../types";
import { generateCategoricalDistractors, generateDistractors, getRandomInt, pickRandom } from "../solver";

export function generateCaseletSet(difficulty: DILRDifficulty): DILRSet {
  // Scenario: EdTech / FinTech subscription & user acquisition cohort analysis
  const cohorts = [
    { city: "Bengaluru", tier: "Tier 1" },
    { city: "Pune", tier: "Tier 2" },
    { city: "Indore", tier: "Tier 3" },
  ];

  const totalRegistered = getRandomInt(120, 180) * 1000; // e.g. 150,000
  // Distribution across 3 cities
  const blrRatio = 5;
  const puneRatio = 3;
  const indoreRatio = 2;
  const totalRatio = blrRatio + puneRatio + indoreRatio; // 10

  const regBlr = (totalRegistered * blrRatio) / totalRatio;
  const regPune = (totalRegistered * puneRatio) / totalRatio;
  const regIndore = (totalRegistered * indoreRatio) / totalRatio;

  // Conversion rate to Paid Pro plan
  const crBlr = 18; // %
  const crPune = 12; // %
  const crIndore = 8; // %

  const paidBlr = Math.round((regBlr * crBlr) / 100);
  const paidPune = Math.round((regPune * crPune) / 100);
  const paidIndore = Math.round((regIndore * crIndore) / 100);
  const totalPaid = paidBlr + paidPune + paidIndore;

  // Annual Subscription Fee per Pro User
  const feeBlr = 4500;
  const feePune = 3600;
  const feeIndore = 2800;

  const revBlr = (paidBlr * feeBlr) / 10000000; // in Cr
  const revPune = (paidPune * feePune) / 10000000;
  const revIndore = (paidIndore * feeIndore) / 10000000;
  const totalRev = Number((revBlr + revPune + revIndore).toFixed(2));

  // Prose description hiding numbers
  const narrative = `EduVantage, an executive upskilling and certification EdTech platform, onboarded a total of ${(
    totalRegistered / 1000
  ).toLocaleString("en-IN")} thousand registered users during the previous fiscal year across three primary hub cities: Bengaluru, Pune, and Indore.

The registered user base across Bengaluru, Pune, and Indore was distributed in the ratio of 5 : 3 : 2, respectively.

Key commercial conversion metrics observed across the hubs were as follows:
• In Bengaluru, 18% of the registered users upgraded to the Paid Annual Pro tier at a subscription fee of ₹4,500 per learner.
• In Pune, 12% of the registered learners converted to the Paid Annual Pro tier, with an annual subscription fee of ₹3,600 per learner.
• In Indore, 8% of the registered learners upgraded to the Paid Annual Pro tier, with an annual subscription price of ₹2,800 per learner.
• Users who did not upgrade remained on the free community tier and yielded zero subscription revenue.`;

  const questions: DILRQuestion[] = [];

  // Question 1: Total number of Paid Pro Subscribers
  const q1Distractors = generateDistractors(
    totalPaid,
    (v) => Math.round(v).toLocaleString("en-IN"),
    {
      offByOne: totalPaid + 1500,
      commonTraps: [Math.round((totalRegistered * 0.12)), paidBlr + paidPune],
    }
  );

  questions.push({
    id: `case-q1-${Date.now()}`,
    questionNumber: 1,
    questionText: `What was the total number of users across all three cities combined who upgraded to the Paid Annual Pro tier?`,
    questionType: "MCQ",
    options: q1Distractors.options,
    correctAnswer: q1Distractors.correctLabel,
    explanation: {
      detailed: `Calculate the registered user count for each city using the 5:3:2 ratio, then apply each city's conversion rate:`,
      steps: [
        `Total Registered = ${totalRegistered.toLocaleString("en-IN")}.`,
        `Bengaluru = 5/10 × ${totalRegistered} = ${regBlr.toLocaleString("en-IN")}. Paid = 18% of ${regBlr} = ${paidBlr.toLocaleString("en-IN")}.`,
        `Pune = 3/10 × ${totalRegistered} = ${regPune.toLocaleString("en-IN")}. Paid = 12% of ${regPune} = ${paidPune.toLocaleString("en-IN")}.`,
        `Indore = 2/10 × ${totalRegistered} = ${regIndore.toLocaleString("en-IN")}. Paid = 8% of ${regIndore} = ${paidIndore.toLocaleString("en-IN")}.`,
        `Total Paid Subscribers = ${paidBlr.toLocaleString("en-IN")} + ${paidPune.toLocaleString("en-IN")} + ${paidIndore.toLocaleString("en-IN")} = ${totalPaid.toLocaleString("en-IN")}.`,
      ],
      shortcut: `Tabulate the 3 lines quickly on your scratchpad: Registered × Conversion% = Paid Learners.`,
    },
    estimatedTimeSec: 90,
    skillTested: "Textual Extraction & Matrix Formulation",
  });

  // Question 2: Total Revenue in ₹ Crores
  const q2Distractors = generateDistractors(
    totalRev,
    (v) => `₹${v.toFixed(2)} Cr`,
    {
      offByOne: Number((totalRev + 1.8).toFixed(2)),
      inverted: Number((revBlr).toFixed(2)),
    }
  );

  questions.push({
    id: `case-q2-${Date.now()}`,
    questionNumber: 2,
    questionText: `What was the total subscription revenue (in ₹ Crores) generated by EduVantage from the Paid Annual Pro users across the three cities combined?`,
    questionType: "MCQ",
    options: q2Distractors.options,
    correctAnswer: q2Distractors.correctLabel,
    explanation: {
      detailed: `Multiply Paid users in each city by their respective fee and aggregate in Crores (1 Cr = 10,000,000):`,
      steps: [
        `Bengaluru: ${paidBlr} × ₹4,500 = ₹${(paidBlr * feeBlr).toLocaleString("en-IN")} = ₹${revBlr.toFixed(2)} Cr.`,
        `Pune: ${paidPune} × ₹3,600 = ₹${(paidPune * feePune).toLocaleString("en-IN")} = ₹${revPune.toFixed(2)} Cr.`,
        `Indore: ${paidIndore} × ₹2,800 = ₹${(paidIndore * feeIndore).toLocaleString("en-IN")} = ₹${revIndore.toFixed(2)} Cr.`,
        `Total Subscription Revenue = ₹${revBlr.toFixed(2)} + ₹${revPune.toFixed(2)} + ₹${revIndore.toFixed(2)} = ₹${totalRev} Cr.`,
      ],
      shortcut: `Factor out 1,000s in fees to speed up multiplication.`,
    },
    estimatedTimeSec: 100,
    skillTested: "Multi-Tier Value Monetization",
  });

  // Question 3: TITA - Difference between Bengaluru and Pune paid subscribers
  const diffPaid = paidBlr - paidPune;

  questions.push({
    id: `case-q3-${Date.now()}`,
    questionNumber: 3,
    questionText: `By how many subscribers did the number of Paid Annual Pro learners in Bengaluru exceed that in Pune? (Enter integer value only)`,
    questionType: "TITA",
    options: [],
    correctAnswer: diffPaid.toString(),
    explanation: {
      detailed: `Subtract Pune's paid subscriber count from Bengaluru's paid subscriber count.`,
      steps: [
        `Paid learners in Bengaluru = ${paidBlr.toLocaleString("en-IN")}.`,
        `Paid learners in Pune = ${paidPune.toLocaleString("en-IN")}.`,
        `Difference = ${paidBlr} - ${paidPune} = ${diffPaid.toLocaleString("en-IN")}.`,
      ],
      observation: `CAT often uses TITA for intermediate differences derived from caselet tables.`,
    },
    estimatedTimeSec: 60,
    skillTested: "Direct Set Subtraction in Caselets",
  });

  // Question 4: Overall Average Conversion Rate (%)
  const overallCr = Number(((totalPaid / totalRegistered) * 100).toFixed(2));
  const q4Distractors = generateDistractors(
    overallCr,
    (v) => `${v.toFixed(2)}%`,
    {
      inverted: Number(((crBlr + crPune + crIndore) / 3).toFixed(2)), // trap: simple mean (12.67%)
      offByOne: Number((overallCr + 1.5).toFixed(2)),
    }
  );

  questions.push({
    id: `case-q4-${Date.now()}`,
    questionNumber: 4,
    questionText: `What was the overall effective conversion rate (percentage of total registered users who upgraded to Paid Annual Pro) across the company?`,
    questionType: "MCQ",
    options: q4Distractors.options,
    correctAnswer: q4Distractors.correctLabel,
    explanation: {
      detailed: `Effective Conversion Rate = (Total Paid Users / Total Registered Users) × 100.`,
      steps: [
        `Total Paid Users = ${totalPaid.toLocaleString("en-IN")}.`,
        `Total Registered Users = ${totalRegistered.toLocaleString("en-IN")}.`,
        `Effective Conversion Rate = (${totalPaid} / ${totalRegistered}) × 100 = ${overallCr}%.`,
      ],
      shortcut: `Weighted average: (5 × 18% + 3 × 12% + 2 × 8%) / 10 = (90 + 36 + 16) / 10 = 142 / 10 = 14.2%. (Matches exact math in a flash!).`,
      commonMistake: `Taking the unweighted arithmetic mean of conversion percentages: (18 + 12 + 8) / 3 = 12.67%.`,
    },
    estimatedTimeSec: 80,
    skillTested: "Weighted Mean in Conversion Funnels",
  });

  return {
    id: `di-caselet-${Date.now()}-${getRandomInt(100, 999)}`,
    section: "DI",
    topic: "caselet",
    topicTitle: "Unstructured Business Caselets & Cohort Funnels",
    difficulty,
    title: "EduVantage Upskilling Cohort Funnel Analysis",
    description: narrative,
    dataset: { totalRegistered, regBlr, regPune, regIndore, paidBlr, paidPune, paidIndore, totalRev },
    visualizationType: "caselet",
    visualizationData: {
      scenarioTitle: "EduVantage — Regional User Acquisition & Monetization Funnel",
      narrative,
      summaryBullets: [
        `Total Registered Cohort: ${(totalRegistered / 1000).toLocaleString("en-IN")}k users across Bengaluru, Pune, and Indore`,
        `User Base Proportions: Bengaluru (5) : Pune (3) : Indore (2)`,
        `Paid Annual Pro Tier Conversion: Bengaluru (18%), Pune (12%), Indore (8%)`,
        `Tier Pricing: Bengaluru (₹4,500), Pune (₹3,600), Indore (₹2,800)`,
      ],
    },
    estimatedTimeMin: difficulty === "CAT_HARD" ? 14 : 10,
    questions,
    tags: ["Caselet DI", "Weighted Averages", "Funnel Analytics", "CAT DILR"],
  };
}
