import { DILRDifficulty, DILRQuestion, DILRSet } from "../types";
import { generateDistractors, getRandomInt, pickRandom } from "../solver";

interface PieSegment {
  name: string;
  percentage: number;
  color: string;
}

export function generatePieChartSet(difficulty: DILRDifficulty): DILRSet {
  const industries = [
    {
      title: "Global Enterprise Cloud Infrastructure Market",
      unit: "$ Billion",
      totalMarket: getRandomInt(240, 360),
      currency: "$",
      segments: [
        { name: "Amazon Web Services (AWS)", basePct: 31, color: "#6366f1" },
        { name: "Microsoft Azure", basePct: 24, color: "#06b6d4" },
        { name: "Google Cloud Platform", basePct: 13, color: "#10b981" },
        { name: "Alibaba Cloud", basePct: 7, color: "#f59e0b" },
        { name: "Oracle Cloud Infrastructure", basePct: 5, color: "#ec4899" },
      ],
    },
    {
      title: "Domestic FMCG Packaged Food Market",
      unit: "₹ Thousand Crore",
      totalMarket: getRandomInt(180, 260),
      currency: "₹",
      segments: [
        { name: "Dairy & Beverage Essentials", basePct: 32, color: "#6366f1" },
        { name: "Biscuits & Bakery", basePct: 22, color: "#06b6d4" },
        { name: "Snacks & Savouries", basePct: 15, color: "#10b981" },
        { name: "Ready-to-Eat & Noodles", basePct: 9, color: "#f59e0b" },
        { name: "Chocolates & Confectionery", basePct: 6, color: "#ec4899" },
      ],
    },
  ];

  const ind = pickRandom(industries);
  const totalMarket = ind.totalMarket;

  // Jiggle percentages slightly while ensuring exact sum = 100
  let currentSum = 0;
  const segments: PieSegment[] = [];

  ind.segments.forEach((s) => {
    const jitter = getRandomInt(-2, 2);
    const pct = Math.max(3, s.basePct + jitter);
    currentSum += pct;
    segments.push({
      name: s.name,
      percentage: pct,
      color: s.color,
    });
  });

  const othersPct = 100 - currentSum;
  segments.push({
    name: "Others & Regional Players",
    percentage: othersPct,
    color: "#94a3b8", // slate
  });

  // Calculate absolute values for each segment
  const segValues: Record<string, number> = {};
  segments.forEach((s) => {
    segValues[s.name] = Number(((s.percentage / 100) * totalMarket).toFixed(2));
  });

  const questions: DILRQuestion[] = [];

  // Question 1: Central Angle Subtended (Degrees)
  const targetSeg = segments[1]; // e.g. second largest
  const angle = Number((targetSeg.percentage * 3.6).toFixed(1));
  const q1Distractors = generateDistractors(
    angle,
    (v) => `${v.toFixed(1)}°`,
    {
      inverted: Number((targetSeg.percentage * 3.0).toFixed(1)), // trap: using 300 or 100
      offByOne: Number((angle + 5.4).toFixed(1)),
    }
  );

  questions.push({
    id: `pie-q1-${Date.now()}`,
    questionNumber: 1,
    questionText: `In the pie chart, what is the measure of the central angle (in degrees) subtended by the sector corresponding to '${targetSeg.name}'?`,
    questionType: "MCQ",
    options: q1Distractors.options,
    correctAnswer: q1Distractors.correctLabel,
    explanation: {
      detailed: `Central angle for any slice in a circular pie chart = (Percentage / 100) × 360° = Percentage × 3.6°.`,
      steps: [
        `Market share of ${targetSeg.name} = ${targetSeg.percentage}%.`,
        `Angle = ${targetSeg.percentage} × 3.6° = ${angle}°.`,
      ],
      shortcut: `Multiply by 3.6 directly or do (Percentage × 18) / 5.`,
      commonMistake: `Multiplying percentage by 3.0 or failing to account for full 360° circle circumference.`,
    },
    estimatedTimeSec: 60,
    skillTested: "Angular Transformation of Percentage Slices",
  });

  // Question 2: Absolute Revenue Calculation
  const segA = segments[0];
  const segB = segments[2];
  const combinedRev = Number(((segA.percentage + segB.percentage) * (totalMarket / 100)).toFixed(2));
  const q2Distractors = generateDistractors(
    combinedRev,
    (v) => `${ind.currency}${v.toFixed(1)} ${ind.unit.replace("₹", "").replace("$", "")}`,
    {
      offByOne: Number((combinedRev + 12).toFixed(1)),
    }
  );

  questions.push({
    id: `pie-q2-${Date.now()}`,
    questionNumber: 2,
    questionText: `What is the combined market revenue generated by '${segA.name}' and '${segB.name}'?`,
    questionType: "MCQ",
    options: q2Distractors.options,
    correctAnswer: q2Distractors.correctLabel,
    explanation: {
      detailed: `Sum the percentage shares of both players and compute the portion of total market size.`,
      steps: [
        `Total market size = ${ind.currency}${totalMarket} ${ind.unit.replace("₹", "").replace("$", "")}.`,
        `Share of ${segA.name} = ${segA.percentage}%.`,
        `Share of ${segB.name} = ${segB.percentage}%.`,
        `Combined share = ${segA.percentage}% + ${segB.percentage}% = ${segA.percentage + segB.percentage}%.`,
        `Combined value = ${segA.percentage + segB.percentage}% of ${totalMarket} = ${ind.currency}${combinedRev} ${ind.unit.replace("₹", "").replace("$", "")}.`,
      ],
      shortcut: `Combine percentages first before multiplying with total market base.`,
    },
    estimatedTimeSec: 75,
    skillTested: "Linear Scaling from Percentage Base",
  });

  // Question 3: TITA - Absolute Difference between Market Leader and Runner Up
  const leaderVal = (segments[0].percentage / 100) * totalMarket;
  const runnerUpVal = (segments[1].percentage / 100) * totalMarket;
  const diffVal = Math.round(leaderVal - runnerUpVal);

  questions.push({
    id: `pie-q3-${Date.now()}`,
    questionNumber: 3,
    questionText: `What is the absolute difference between the revenue generated by the market leader (${segments[0].name}) and the runner-up (${segments[1].name})? (Round to nearest integer, enter number only)`,
    questionType: "TITA",
    options: [],
    correctAnswer: diffVal.toString(),
    explanation: {
      detailed: `Calculate the difference in percentage points and apply to total market size.`,
      steps: [
        `Leader (${segments[0].name}) share = ${segments[0].percentage}%.`,
        `Runner-up (${segments[1].name}) share = ${segments[1].percentage}%.`,
        `Difference in percentage points = ${segments[0].percentage}% - ${segments[1].percentage}% = ${segments[0].percentage - segments[1].percentage}%.`,
        `Absolute Difference = (${segments[0].percentage - segments[1].percentage}% / 100) × ${totalMarket} = ${diffVal}.`,
      ],
      shortcut: `Difference in % = (${segments[0].percentage} - ${segments[1].percentage})%. Multiply by total market ${totalMarket} directly.`,
    },
    estimatedTimeSec: 70,
    skillTested: "Differential Extraction & TITA Precision",
  });

  // Question 4: CAT-Level Elasticity / Growth Projection
  const fastMover = segments[2];
  const marketExpansionPct = 20; // market grows 20%
  const newFastMoverShare = fastMover.percentage + 4; // gains 4 pp share
  const oldRev = (fastMover.percentage / 100) * totalMarket;
  const newTotalMarket = totalMarket * (1 + marketExpansionPct / 100);
  const newRev = (newFastMoverShare / 100) * newTotalMarket;
  const actualGrowth = Number((((newRev - oldRev) / oldRev) * 100).toFixed(1));

  const q4Distractors = generateDistractors(
    actualGrowth,
    (v) => `${v.toFixed(1)}%`,
    {
      inverted: Number((marketExpansionPct + (newFastMoverShare - fastMover.percentage)).toFixed(1)), // common blunder: just adding %
      offByOne: Number((actualGrowth + 6.5).toFixed(1)),
    }
  );

  questions.push({
    id: `pie-q4-${Date.now()}`,
    questionNumber: 4,
    questionText: `Suppose in the subsequent fiscal year, the overall ${ind.title} expands by ${marketExpansionPct}%, and the market share of '${fastMover.name}' increases from ${fastMover.percentage}% to ${newFastMoverShare}%. By what percentage will the actual revenue of '${fastMover.name}' increase?`,
    questionType: "MCQ",
    options: q4Distractors.options,
    correctAnswer: q4Distractors.correctLabel,
    explanation: {
      detailed: `Revenue depends on both the expansion of the entire market and the change in individual market share.`,
      steps: [
        `Initial Revenue of ${fastMover.name} = ${fastMover.percentage}% × ${totalMarket} = ${oldRev.toFixed(2)}.`,
        `New Total Market Size = ${totalMarket} × 1.${marketExpansionPct} = ${newTotalMarket.toFixed(2)}.`,
        `New Revenue of ${fastMover.name} = ${newFastMoverShare}% × ${newTotalMarket.toFixed(2)} = ${newRev.toFixed(2)}.`,
        `Percentage Revenue Growth = [(${newRev.toFixed(2)} - ${oldRev.toFixed(2)}) / ${oldRev.toFixed(2)}] × 100 = ${actualGrowth}%.`,
      ],
      shortcut: `Multiplier formula: New Rev / Old Rev = (New Share / Old Share) × (New Total / Old Total) = (${newFastMoverShare} / ${fastMover.percentage}) × 1.${marketExpansionPct}. Subtract 1 and multiply by 100.`,
      commonMistake: `Simply adding the percentage point gain (4%) to the market expansion rate (20%) to conclude 24%—this ignores compounding expansion on higher market share!`,
    },
    estimatedTimeSec: 120,
    skillTested: "Compounded Growth & Market Dynamics",
  });

  return {
    id: `di-pie-${Date.now()}-${getRandomInt(100, 999)}`,
    section: "DI",
    topic: "pie-chart",
    topicTitle: "Pie Charts & Market Breakdown",
    difficulty,
    title: `${ind.title} — Market Share Distribution`,
    description: `The pie chart below exhibits the market share distribution of the ${ind.title}. The total valuation of the market is estimated at ${ind.currency}${totalMarket} ${ind.unit.replace("₹", "").replace("$", "")}. All individual slices denote the percentage share of each player, which sum up to exactly 100%.`,
    dataset: { industry: ind.title, totalMarket, segments },
    visualizationType: "pie",
    visualizationData: {
      title: `${ind.title} (Total: ${ind.currency}${totalMarket} ${ind.unit.replace("₹", "").replace("$", "")})`,
      segments: segments.map((s) => ({
        name: s.name,
        value: s.percentage,
        color: s.color,
      })),
    },
    estimatedTimeMin: difficulty === "CAT_HARD" ? 12 : 8,
    questions,
    tags: ["Pie Chart", "Market Share", "Angular Geometry", "Revenue Elasticity", "CAT DILR"],
  };
}
